### ISSUE TITLE
Missing preferences icon

### ISSUE THREAD

**Issue by Philip-Scott** [babluboy/bookworm#1]
Yeah, the icon is missing like you said ;) 

But as per the rest of the elementary apps, you should add the About item to the .desktop's as a quick list item instead of adding it on the menu. You know, for consistency :)

**Comment by babluboy** [comment]
Fixed the issue with About Dialog and the missing icon for Preferences.
Already add the AboutDialog to the .desktop, but have not removed it from the Preferences as I don't have any option in the Preferences for the time being. Have added a menu item called Font but have not implemented the same yet.

**Comment by babluboy** [comment]
Just out of interest, what is the reason to remove the About from the app preference menu.

**Comment by Philip-Scott** [comment]
Well, it's really just for consistency with the rest of the elementary apps like Mail or Scratch :)
