### ISSUE TITLE
keyboard shortcuts?

### ISSUE THREAD

**Issue by unhammer** [babluboy/bookworm#100]
Is there a listing somewhere of keyboard shortcuts? 

In particular, how do I go next/previous page?

**Comment by babluboy** [comment]
@unhammer The next/previous pages work with the right/left arrow keys. Have a look at the bookworm website for all the currently available shortcuts. I intend to keep updating this website as I add more shortcuts.
https://babluboy.github.io/bookworm/

**Comment by unhammer** [comment]
Thanks! But I don't see left/right mentioned, only things like `ctrl+'-'` and `F11`

**Comment by babluboy** [comment]
Good spot ! Probably since it was the most used shortcut that I forgot to mention it on the website. I have added this now and updated the shortcut list on the website
