### ISSUE TITLE
Highlight searched text and scroll to text position

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#103]
When a search result is clicked, the page should be automatically scrolled to the position where the text appears and if more than one occurrence of the searched text exist on a page they should be highlighted in fluorescent yellow

**Comment by babluboy** [comment]
Pushed an update to highlight search results and auto scroll to the first result (if there are multiple occurrences on the page)...

however, currently the results are taking a bit long to come up, the result page is shown after all results are found - will try to improve this, so that the results page is shown at once and the individual results are seen as soon as they are found... 

![screenshot from 2017-08-30 14 16 48](https://user-images.githubusercontent.com/14061478/29878630-f49ecf54-8d9a-11e7-98bc-84b6c8829f34.png)

**Comment by sojusnik** [comment]
The new search works quite well, thanks!

I've stumbled upon severals bugs though:

The highlighted search results always have the same format as the search query. So if I write `PRINCE` in the search field, my search results would always be depicted as `PRINCE`. The same is true for `PRince` and so on. Try it with [this](https://mega.nz/#!fsxVmAhC!dGncKDhbE51jliWJz76z0MVDRiiByi7H_tyao2FlK1U) epub.

Then Bookworm always jumps to the first search result, although another one, f.i., the third one is selected.

The highlighted words don't disappear, when the search field is cleared.

**Comment by babluboy** [comment]
@sojusnik Many thanks for testing and reporting the issues. Will try and fix these and update back. The last one is the most problematic one in my view while the other two are less of an issue...

**Comment by babluboy** [comment]
Pushed an update to make search async - results are shown as they are found and the user does not have to wait for all results to be found to action a result link...

**Comment by babluboy** [comment]
Pushed an update for fixing the following:
1- Search results highlighted show the original text and not what is being search for (i.e. searching for PRInce will highlight Prince as Prince is the original text in the book)
2- The highlighted text is the same occurrence as the one selected by the user from the search result (not the first occurrence as was the issue earlier)
3- Added the name of the chapter containing the line of the search result to provide some extra information to the user
4- Bookworm now remembers the tab within Info that was last visited - this is helpful to go back to the search result with just one click (earlier the info tab always defaulted to the contents view)

In my view, it is unnecessary to clear the result highlight on a page when the search box is cleared as this happens when the page is navigated or a new search is executed. 

The only issue I see is when the search text spans across a line the highlighting does not work - will try and fix the same.

**Comment by babluboy** [comment]
Fixed the issue where the search phrase spans over two lines - retrying the search phrase by removing one word at a time from the left until the phrase is found seems to work. Closing this issue.
