### ISSUE TITLE
Honor user preference for `$PREFIX`

### ISSUE THREAD

**Issue by shinenelson** [babluboy/bookworm#105]
( continuing from https://github.com/babluboy/bookworm/issues/94#issuecomment-318757230 )

`make install` tries to create a directory in `/opt` without honoring `$PREFIX` from line 264 of `cmake_install.cmake`. And without elevated privileges, it just breaks.

Is it really necessary to install scripts to a directory rather than the user's preferred `$PREFIX` directory? And especially when it requires elevated privileges too?

The install would probably complete successfully if I ran it with `sudo` but my intention was to install to a custom directory that does not require elevated privileges. It would be great if you supported that as well.

**Comment by babluboy** [comment]
The reason for choosing /opt for dependent libraries came from here:
http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html

The path information is held in the src/constants.vala where you can modify the MONITOR_SCRIPT_LOCATION and MOBIUNPACK_SCRIPT_LOCATION to your desired location and then also modify the CMakeLists.txt accordingly and build.

I'm planning to move all the project resources into the build executable using GResources (#81). When that is done, there will be no dependency on external directories. Hopefully the above will work to customize to your preferences.

**Comment by babluboy** [comment]
Just pushed an update to master to modify CMakeLists to remove dependency on /opt - now all data for bookworm is under /usr/share/bookworm as referenced in the $PREFIX
Hopefully this works for you, please re-open in case of further issue.

**Comment by shinenelson** [comment]
Thanks for the update.

While the change enabled me successfully compile without providing elevated privileges and the application started fine, but there were issues.

1. The `install configuration` log line in the build log was empty. 
It seems `CMAKE_INSTALL_CONFIG_NAME` was not set ( because `BUILD_TYPE` was not defined (?) )
Is that expected? Is `BUILD_TYPE` a elementary parameter and not available for Ubuntu?
2. While the scripts were installed to `$PREFIX/share` as expected, I think they were missed to be updated in some part of the source code. I hit some errors upon opening `bookworm` fresh out of install : 
```
[_LOG_LEVEL_INFO 22:15:47.253371] Application.vala:153: Bookworm version: 0.9.1
[_LOG_LEVEL_INFO 22:15:47.253414] Application.vala:155: Kernel version: 4.4.0-89-generic
[_LOG_LEVEL_WARN 22:15:47.308148] bookworm.vala:355: Image could not be loaded. Error:Failed to open file '/usr/share/bookworm/icons/hicolor/16x16/actions/bookworm-selection-option.svg': No such file or directory
[_LOG_LEVEL_FATAL 22:15:47.308825] granite_widgets_mode_button_append: assertion 'w != NULL' failed
[_LOG_LEVEL_FATAL 22:15:47.308844] Bookworm will not function properly.
[_LOG_LEVEL_FATAL 22:15:47.308862] granite_widgets_mode_button_append: assertion 'w != NULL' failed
[_LOG_LEVEL_FATAL 22:15:47.308874] Bookworm will not function properly.
[_LOG_LEVEL_FATAL 22:15:47.308903] granite_widgets_mode_button_set_active: assertion '_tmp2_' failed
[_LOG_LEVEL_FATAL 22:15:47.308924] Bookworm will not function properly.
[_LOG_LEVEL_FATAL 22:15:47.348189] [Gtk] gtk_box_pack: assertion '_gtk_widget_get_parent (child) == NULL' failed
[_LOG_LEVEL_FATAL 22:15:47.348228] Bookworm will not function properly.
[_LOG_LEVEL_WARN 22:15:47.355208] [GLib] Invalid file descriptor.
[_LOG_LEVEL_WARN 22:15:47.355297] [GLib] Invalid file descriptor.
[_LOG_LEVEL_WARN 22:15:47.355368] [GLib] Invalid file descriptor.
[_LOG_LEVEL_WARN 22:15:47.355438] [GLib] Invalid file descriptor.
[_LOG_LEVEL_FATAL 22:15:47.360253] file /home/shine/dev/git/bookworm/src/library.vala: line 112: uncaught error: Failed to open file '/usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-placeholder-cover.png': No such file or directory (g-file-error-quark, 4)
[_LOG_LEVEL_FATAL 22:15:47.360289] Bookworm will not function properly.
[_LOG_LEVEL_FATAL 22:15:47.449772] file /home/shine/dev/git/bookworm/src/library.vala: line 112: uncaught error: Failed to open file '/usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-placeholder-cover.png': No such file or directory (g-file-error-quark, 4)
[_LOG_LEVEL_FATAL 22:15:47.449795] Bookworm will not function properly.
[_LOG_LEVEL_FATAL 22:15:47.513569] file /home/shine/dev/git/bookworm/src/library.vala: line 112: uncaught error: Failed to open file '/usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-placeholder-cover.png': No such file or directory (g-file-error-quark, 4)
[_LOG_LEVEL_FATAL 22:15:47.513597] Bookworm will not function properly.
[_LOG_LEVEL_FATAL 22:15:47.518797] file /home/shine/dev/git/bookworm/src/library.vala: line 112: uncaught error: Failed to open file '/usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-placeholder-cover.png': No such file or directory (g-file-error-quark, 4)
[_LOG_LEVEL_FATAL 22:15:47.518826] Bookworm will not function properly.
[_LOG_LEVEL_FATAL 22:15:47.521099] file /home/shine/dev/git/bookworm/src/library.vala: line 112: uncaught error: Failed to open file '/usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-placeholder-cover.png': No such file or directory (g-file-error-quark, 4)
[_LOG_LEVEL_FATAL 22:15:47.521134] Bookworm will not function properly.
[_LOG_LEVEL_WARN 22:15:49.934741] utils.vala:109: Error encountered in execution of sync command [/usr/share/bookworm/scripts/tasks/com.github.babluboy.bookworm.monitor.sh /home/shine/.config/bookworm/user_crontab_backup.txt /tmp/bookworm/bookworm_user_crontab_temp.txt]: Failed to execute child process "/usr/share/bookworm/scripts/tasks/com.github.babluboy.bookworm.monitor.sh" (No such file or directory)
```
I guess they're looking for `/usr`(the default `CMAKE` location)`/share` instead of `$PREFIX/share`.

**Comment by babluboy** [comment]
@shinenelson You are correct the code looks for /usr/share as the location for all resources (icons, data, scripts, etc.). I will need to figure out how to get the value of the $PREFIX within the code and use the same instead. Any ideas?

**Comment by shinenelson** [comment]
My intention was to compile, install and run the application without elevated privileges. So, if I were to install it to `/usr/share`, I'd need to provide elevated privileges.

Also, doesn't a symlink from a system directory to anywhere else seem like a hack that isn't desired?

BTW, did you get some time to look into how to get this to go?
> I will need to figure out how to get the value of the $PREFIX within the code and use the same instead.

This could be something of a dynamic build parameter that you should be able to configure at build-time; but I'm not a vala guy, so, I wouldn't know how.

**Comment by babluboy** [comment]
@shinenelson I finally figured out how to set the install directory based on the $PREFIX in the cmakelists - this is covered in #132. When I push the update your issue will also be solved and the code will not look for /usr/share for resources as a hard coded path....
