### ISSUE TITLE
Some epub books don't open

### ISSUE THREAD

**Issue by aggiebill** [babluboy/bookworm#106]
Some of my epub books do not open.  One common issue might be is that both of them are from "No Starch Press".  I can open them in Calibre without issue.  The error message says the mime-type does not match.  

I would be more than happy to do some more in depth diagnostics.

**Comment by babluboy** [comment]
@aggiebill Thanks for raising this issue, will hopefully lead to better ePub support.

Lets try and debug this. If you go into your bookworm cache folder : `~/.config/bookworm/books/` and then into one of the ePubs which is having an issue. You should see a file called `mimetype` and the contents of the same will be `application/epub+zip`
Thats is what the code tries to check for after unzipping the contents of the ePub

**Comment by aggiebill** [comment]
Here is one file:
`1 bill@toy-putter2:~/.config/bookworm/books/Make_Electronics.epub⟫ ll
total 36
drwxr-xr-x  4 bill bill  4096 Jul 31 20:47 ./
drwxr-xr-x 47 bill bill 12288 Jul 31 20:47 ../
drwxr-xr-x  2 bill bill  4096 Jul 31 20:47 META-INF/
----------  1 bill bill    20 Dec  7  2009 mimetype
drwxr-xr-x  3 bill bill  4096 Jul 31 20:47 OEBPS/
bill@toy-putter2:~/.config/bookworm/books/Make_Electronics.epub⟫ sudo cat mimetype
[sudo] password for bill:
application/epub+zipbill@toy-putter2:~/.config/bookworm/books/Make_Electronics.epub⟫
`

`bill@toy-putter2:~/.config/bookworm/books/makersguidetothezombieapocalypse.epub⟫ ll
total 48
drwxr-xr-x  4 bill bill  4096 Jul 31 20:47 ./
drwxr-xr-x 48 bill bill 12288 Jul 31 20:52 ../
-rw-r--r--  1 bill bill   993 Oct 13  2015 iTunesMetadata.plist
drwxr-xr-x  2 bill bill  4096 Oct 13  2015 META-INF/
-rw-r--r--  1 bill bill    20 Apr  9  2011 mimetype
drwxr-xr-x  3 bill bill  4096 Oct 13  2015 OEBPS/
bill@toy-putter2:~/.config/bookworm/books/makersguidetothezombieapocalypse.epub⟫ cat mimetype
application/epub+zipbill@toy-putter2:~/.config/bookworm/books/makersguidetothezombieapocalypse.epub⟫ cat iTunesMetadata.plist
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
        <key>artistName</key>
        <string>Simon Monk</string>
        <key>book-info</key>
        <dict>
                <key>cover-image-hash</key>
                <string>595EF4E6E7C84BDFFE396E90FBA8BE6C</string>
                <key>cover-image-path</key>
                <string>OEBPS/html/graphics/9781593276676.jpg</string>
                <key>mime-type</key>
                <string>application/epub+zip</string>
                <key>package-file-hash</key>
                <string>81C282E5065CF21161D3C9E919A38642</string>
                <key>publisher-unique-id</key>
                <string>9781593276676</string>
                <key>unique-id</key>
                <integer>-1341333950698754784</integer>
                <key>update-level</key>
                <integer>2</integer>
        </dict>
        <key>itemName</key>
        <string>The Maker’s Guide to the Zombie Apocalypse</string>
        <key>playlistName</key>
        <string>The Maker’s Guide to the Zombie Apocalypse</string>
        <key>releaseDate</key>
        <string>2016</string>
</dict>
</plist>
bill@toy-putter2:~/.config/bookworm/books/makersguidetothezombieapocalypse.epub⟫
`

**Comment by aggiebill** [comment]
[debug.txt](https://github.com/babluboy/bookworm/files/1189227/debug.txt)

Here is the debug.txt file for those two files.

**Comment by babluboy** [comment]
@aggiebill Looking through the debug data, the failure happens after the mime file extracted from the ePub is checked. For some reason the permission on the extracted file is not allowing the file to be read by Bookworm:
`Failed to open file “/home/bill/.config/bookworm/books/Make_Electronics.epub/mimetype”: Permission denied`

I also see you are using sudo to see the contents of the extracted file:
`sudo cat mimetype [sudo] password for bill: application/epub+zip`

I believe this is a permission issue. One way might be to provide read/execute permissions to the epub file before attempting to add it to bookworm. Another way might be to run bookworm under sudo using the terminal to open the epub i.e. 
`sudo bookworm --debug /path/to/file.epub`
And then providing read permissions to the extracted content in under the `/home/bill/.config/bookworm/books` directory so that bookworm is able to read the book contents when run normally

Let me know how it goes...

**Comment by babluboy** [comment]
I downloaded the "Make Electronics" ebook in both ePub and mobi format and Bookworm is able to open both without problems. I have attached the books here just in case it is the same one you were trying to read.
![screenshot from 2017-08-02 21 36 00](https://user-images.githubusercontent.com/14061478/28893798-b2a4a0e6-77ca-11e7-8cbb-cac14de7dd7b.png)



[Make Electronics.zip](https://github.com/babluboy/bookworm/files/1195238/Make.Electronics.zip)

**Comment by babluboy** [comment]
Closing this as it appears to be a permission issue - do let me know if you are seeing the issue persisting...
