### ISSUE TITLE
Insight on Directory Structure?

### ISSUE THREAD

**Issue by Christopher-Foveros** [babluboy/bookworm#107]
This isn't an issue. I'm a Calibre user, and am interested in 'switching readers'.  Calibre has a very good system of folders, and an indexed database. Can you give me any insight as to how the books are organized in your program? I'm assuming there's a root folder.. What's it look like under that? Could I just move/rename my Calibre folder and let it go to town?  Thanks.

**Comment by babluboy** [comment]
Hi there...Bookworm stores it's data under ~/.config/bookworm. However, Bookworm doesn't duplicate the book into its folder structure...

The directory contains a bookworm.db file which contains the meta data of all books in the library like author, title, last read page, etc. It also contains the links to the parsed content and thumbnail image of the books under the sub folders "books" and "covers" respectively....

If cache is turned on in the Preference menu, then the extracted contents of the book are stored in the folder under the sub folder "books" (these are paginated HTML files which bookworm uses). Cover images are also stored in this directory under the sub folder "covers". If no caching is done then bookworm parses the book at its original location every time it is opened for reading...adding a book manually into this folder will have no effect and it will be deleted automatically as an orphaned file having no link to the meta data db...

In the preference menu, the last item allows you to watch for one or more folders to automatically find and add supported books into bookworm...if you can set this as the top level folder in Calibre then all the books should be added into Bookworm ...however you should not delete the books from the Calibre folder as that is where Bookworm will look for the books if caching is not turned on and the ebook files will only be present in those Calibre folders if you want them later for some reason ....

Hopefully the above clarifies...Bookworm is just a manager for your ebook files and does not duplicate the ebook files on your local machine....
