### ISSUE TITLE
Add annotation capabilities

### ISSUE THREAD

**Issue by baimafeima** [babluboy/bookworm#109]
I know bookworm is primarily meant as a simple e-book reader. However, I intend to use it more for reading scientific articles. Would it be possible to add PDF annotation tools and generally improve PDF rendering capabilities or do you think this is rather something for a separate project? Currently, there are not many PDF annotation tools available for Linux-based operating systems.

**Comment by babluboy** [comment]
@baimafeima Thanks for raising this - annotation is definitely a good capability and I will like to add it to bookworm at some point. I can use this issue to keep track and hopefully I will get to it at some point.

Yes, PDF rendering improvement is on my TO-DO list...I am trying to see what can be a better PDF to HTML conversion as the pdftohtml utility is pretty basic and does not render the pages well. I'm tracking this on #82

**Comment by baimafeima** [comment]
Thanks a lot for considering this. I will help track down annotation options and everyone could help by adding to this list:
- https://github.com/lhansford/Footnote

**Comment by babluboy** [comment]
Cross referencing #102 with this - the annotation and highlight can be put in the same context as menu options after the user selects some text on a page...Annotation can be on a tab in the Info section to start with...but can also be made available on a collapsible sidebar as well...

**Comment by babluboy** [comment]
Initial design idea is :
1. Show a right click context menu option to add annotations after selecting text on a page
2. Show a modal dialogue to enter annotation
3. Once Annotated the selected text is shown in green highlight and hyperlinked
4. On click the annotation is shown in a modal dialogue where it can be edited or deleted
5. All annotations in the book are listed on a tab in the Info section arranged by page numbers. On click of any annotation the corresponding page of the book will be opened with the annotated text scrolled to view 

Thoughts?

**Comment by ckrzen** [comment]
Annotations have never been a priority for me. I'll defer to others who
care.

**Comment by babluboy** [comment]
@baimafeima At the moment I'm keeping the annotation data separate from the book (in the Bookworm database) and it is over-layed at view time. Since all books are viewed in HTML format, it makes it easy to apply annotations uniformly for all formats like PDF, ePUB, Mobi, etc. 

I like your thought about adding the annotation data into the book itself - but there are two challenges:
1- At the present time, Bookworm does not update/change the actual eBook
2- I have not seen any standards for annotations and it will surely vary across different eBook formats

So the best I can think of for later design is to have a function to export or embed all meta data for a book (i.e. annotation, bookmarks, ratings, etc) to a format which is standardized and supported by other eBook software and can be imported. But don't think that will happen soon and will be restricted only specific software and format like eVince/PDF.

**Comment by babluboy** [comment]
Pushed an initial version to GH and the daily PPA for annotations.
Creating Annotations (multiple), Persisting the Annotation and displaying it back and Editing Annotations are all working. The following needs to be done:
- Disable creation of annotation in right click context menu when no text is selected
- Remove the annotation when the annotation is updated by deleting the annotated text
- Show all annotations in the Annotation tab under Info and hyperlink them to allow jumping to the page containing the annotation

Some screen shots of the current implementation. Will be great if anyone can test from the daily PPA or build from source on master.

![0-select text for annotation](https://user-images.githubusercontent.com/14061478/31192668-d2586f30-a939-11e7-8c0b-d94a6cd730a5.png)
![1-add annotation](https://user-images.githubusercontent.com/14061478/31192671-d26adb7a-a939-11e7-9491-7c75b19801ec.png)
![2-edit annotation](https://user-images.githubusercontent.com/14061478/31192670-d266c17a-a939-11e7-8cce-f670e06e968f.png)
![3-multiple annotations on page](https://user-images.githubusercontent.com/14061478/31192669-d2645912-a939-11e7-91a7-ccdcafa2f263.png)

**Comment by baimafeima** [comment]
Just came across TagNotate: http://www.tagnotate.com/ which unfortunately is neither open-source nor available cross-platform but it has a unique feature set: the ability to tag annotations to quickly find information within and across documents. Is there a possibility to implement something like this?

**Comment by babluboy** [comment]
@baimafeima Thanks for this - very interesting. I have already implemented annotation list within a book to jump to a page containing that annotation quickly - screen shot below. will push this out shortly.

The taging of annotation is a nice idea to allow searching across the library. Initial thought is to add a text box within the annotation dialog to add tags to a specific annotation and then use the search bar in the library view (which currently filters books on title, authors, tags) to also filter by annotation tags....

![screenshot from 2017-10-09 08 36 02](https://user-images.githubusercontent.com/14061478/31328420-f31410c6-accc-11e7-8df1-002bcbcc8682.png)

**Comment by babluboy** [comment]
Added the final updates to annotations:
1- Removing the annotation text will remove the annotation highlight
2- Tags can be set for a annotated text and these tags can be used to filter books in the library

Will wrap up the annotation feature with this update and do testing to improve the functionality.

![screenshot from 2017-10-15 22 19 16](https://user-images.githubusercontent.com/14061478/31589336-c673c748-b1f7-11e7-946a-16aafcea0c9a.png)
