### ISSUE TITLE
Starts always centered

### ISSUE THREAD

**Issue by sojusnik** [babluboy/bookworm#114]
Bookworm doesn't remember its window position and starts always in the middle of the screen, as [this](https://mega.nz/#!3sRwSYyS!hID9fahZF_tvlUREf6122H8hYIY-zmD1M4ZStOkcD10) video shows.

Happens on Ubuntu 17.04 with Bookworm 0.9.1 from the Launchpad PPA.

**Comment by babluboy** [comment]
@sojusnik Thanks for raising this. Should be a easy one to save the last window position in the gsettings.

**Comment by babluboy** [comment]
Pushed a update to set the window position to the last set position ("remember last position")
https://github.com/babluboy/bookworm/commit/5ad8a7acca001cbf98d16f948854e948d25b5882
