### ISSUE TITLE
Fedora package

### ISSUE THREAD

**Issue by keeferrourke** [babluboy/bookworm#115]
It would be awesome if this application was packaged for Fedora 👍

**Comment by babluboy** [comment]
@keeferrourke While Bookworm is primarily built for elementary os, I have plans to release this to the wider linux community as AppImage/Snaps/Flatpack, etc. But will focus on improving the app and adding some features for now....

Will keep this issue open to remind me of getting it on to Fedora someday, however if you would like to build from source, this thread mentions the details by someone who built it for Fedora:
[https://www.reddit.com/r/linux/comments/69qwdk/why_dont_more_linux_distros_support_elementary_app/](https://www.reddit.com/r/linux/comments/69qwdk/why_dont_more_linux_distros_support_elementary_app/)

**Comment by keeferrourke** [comment]
I managed to build it by following the instructions from your README file, dnf just packages software with different names than apt.

**Comment by keeferrourke** [comment]
FYI commands used to build and run Bookworm on Fedora Workstation 26:
```
git clone https://github.com/babluboy/bookworm.git /tmp/bookworm
sudo dnf install granite-devel vala vala-devel webkitgtk4 webkitgtk4-devel \
         libsqlite3x-devel poppler-utils poppler-devel poppler-glib-devel
cd /tmp/bookworm
cmake -DCMAKE_INSTALL_PREFIX=/usr ../
make
sudo make install
```
The non `*-devel` packages are probably not necessary, but I like to have them installed anyway.

**Comment by babluboy** [comment]
@keeferrourke many thanks for this. If you can fine tune the instructions i.e remove packages if not necessary then I can put up the instructions on the install section:
[https://babluboy.github.io/bookworm/](https://babluboy.github.io/bookworm/)

**Comment by bjs339** [comment]
@keeferrourke Thank you for the instructions. I had to install cmake and gcc-c++ as I did not already have them. I also had to remove the `../` from the cmake line, so it read `cmake -DCMAKE_INSTALL_PREFIX=/usr`. Before removing it I got the message "CMake Error: The source directory "/tmp" does not appear to contain CMakeLists.txt." After that, all was well and the app is installed.

**Comment by Warmuser** [comment]
@keeferrourke how can I solve these problem? 

Github and Cmake are are both installed. I'm on fedora 26.

[vmaccount@localhost bookworm]$ cmake -DCMAKE_INSTALL_PREFIX=/usr ../
CMake Error: The source directory "/tmp" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.

**Comment by babluboy** [comment]
@Warmuser based on the comment above from @keeferrourke : 

> I also had to remove the ../ from the cmake line, so it read 
cmake -DCMAKE_INSTALL_PREFIX=/usr .

you would need to change your cmake command to: 
`cmake -DCMAKE_INSTALL_PREFIX=/usr .`
instead of  : 
`cmake -DCMAKE_INSTALL_PREFIX=/usr ../`

**Comment by keeferrourke** [comment]
@Warmuser looks like you were in the wrong directory. @babluboy seems to have the fix for you :)

**Comment by Warmuser** [comment]
@babluboy and @keeferrourke I tried again and this is the resoult. 

[vmaccount@localhost ~]$ git clone https://github.com/babluboy/bookworm.git /tmp/bookworm
Cloning into '/tmp/bookworm'...
remote: Counting objects: 2843, done.
remote: Total 2843 (delta 0), reused 0 (delta 0), pack-reused 2843
Receiving objects: 100% (2843/2843), 10.81 MiB | 1.21 MiB/s, done.
Resolving deltas: 100% (2039/2039), done.
[vmaccount@localhost ~]$ sudo dnf install granite-devel vala vala-devel webkitgtk4 webkitgtk4-devel \
>          libsqlite3x-devel poppler-utils poppler-devel poppler-glib-devel
[sudo] password for vmaccount: 
Last metadata expiration check: 0:12:56 ago on Thu 12 Oct 2017 12:37:48 PM CEST.
Package granite-devel-0.4.1-1.fc26.x86_64 is already installed, skipping.
Package vala-0.36.5-1.fc26.x86_64 is already installed, skipping.
Package vala-devel-0.36.5-1.fc26.x86_64 is already installed, skipping.
Package webkitgtk4-2.18.0-1.fc26.x86_64 is already installed, skipping.
Package webkitgtk4-devel-2.18.0-1.fc26.x86_64 is already installed, skipping.
Package libsqlite3x-devel-20071018-20.fc26.x86_64 is already installed, skipping.
Package poppler-utils-0.52.0-5.fc26.x86_64 is already installed, skipping.
Package poppler-devel-0.52.0-5.fc26.x86_64 is already installed, skipping.
Package poppler-glib-devel-0.52.0-5.fc26.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[vmaccount@localhost ~]$ cd /tmp/bookworm
[vmaccount@localhost bookworm]$ cmake -DCMAKE_INSTALL_PREFIX=/usr .
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.


-- Configuring incomplete, errors occurred!                                                                                                                  
See also "/tmp/bookworm/CMakeFiles/CMakeOutput.log".                                                                                                         
See also "/tmp/bookworm/CMakeFiles/CMakeError.log".

I don't understand how to proceed. Sorry, but I use fedora about 4 months. I'm not really expert yet. :)

**Comment by keeferrourke** [comment]
Do as your console tells you:
> Tell CMake where to find the compiler by setting either the environment
variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
to the compiler, or to the compiler name if it is in the PATH.

Make sure you have a c++ compiler installed... This can be either `g++` from `gcc` or `clang++` from `clang`.

To get g++ and a number of other packages your probably need to build software, run:
```
sudo dnf group install 'Development Tools'
```

**Comment by Warmuser** [comment]
So, I have to insert "CXX" somewhere into these command "cmake -DCMAKE_INSTALL_PREFIX=/usr ."? I'm not sure but it looks like the "The CXX compiler identification is unknown" so I don't understand why If I have installed the suggested package. #keeferrourke thanks for the help, anyway! :)

This is the resoult of these test after the installation of the developer tools: 

[vmaccount@localhost ~]$ git clone https://github.com/babluboy/bookworm.git /tmp/bookworm
Cloning into '/tmp/bookworm'...
remote: Counting objects: 2847, done.
remote: Compressing objects: 100% (4/4), done.
remote: Total 2847 (delta 0), reused 1 (delta 0), pack-reused 2843
Receiving objects: 100% (2847/2847), 10.81 MiB | 1.18 MiB/s, done.
Resolving deltas: 100% (2039/2039), done.
[vmaccount@localhost ~]$ sudo dnf install granite-devel vala vala-devel webkitgtk4 webkitgtk4-devel \
>          libsqlite3x-devel poppler-utils poppler-devel poppler-glib-devel
[sudo] password for vmaccount: 
Last metadata expiration check: 0:04:06 ago on Fri 13 Oct 2017 08:39:18 AM CEST.
Package granite-devel-0.4.1-1.fc26.x86_64 is already installed, skipping.
Package vala-0.36.5-1.fc26.x86_64 is already installed, skipping.
Package vala-devel-0.36.5-1.fc26.x86_64 is already installed, skipping.
Package webkitgtk4-2.18.0-1.fc26.x86_64 is already installed, skipping.
Package webkitgtk4-devel-2.18.0-1.fc26.x86_64 is already installed, skipping.
Package libsqlite3x-devel-20071018-20.fc26.x86_64 is already installed, skipping.
Package poppler-utils-0.52.0-5.fc26.x86_64 is already installed, skipping.
Package poppler-devel-0.52.0-5.fc26.x86_64 is already installed, skipping.
Package poppler-glib-devel-0.52.0-5.fc26.x86_64 is already installed, skipping.
Dependencies resolved.
Nothing to do.
Complete!
[vmaccount@localhost ~]$ cd /tmp/bookworm
[vmaccount@localhost bookworm]$ cmake -DCMAKE_INSTALL_PREFIX=/usr .
-- The C compiler identification is GNU 7.2.1
-- The CXX compiler identification is unknown
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
CMake Error at CMakeLists.txt:2 (project):
  No CMAKE_CXX_COMPILER could be found.

  Tell CMake where to find the compiler by setting either the environment
  variable "CXX" or the CMake cache entry CMAKE_CXX_COMPILER to the full path
  to the compiler, or to the compiler name if it is in the PATH.

                                                                                                                             
-- Configuring incomplete, errors occurred!                                                                                  
See also "/tmp/bookworm/CMakeFiles/CMakeOutput.log".
See also "/tmp/bookworm/CMakeFiles/CMakeError.log".
[vmaccount@localhost bookworm]$

**Comment by keeferrourke** [comment]
@Warmuser I'd suggest asking on http://ask.fedoraproject.org. This issue is getting cluttered and off-topic. I'll try to build an RPM at some point in the future, but it probably won't be until December because I'm in the middle of midterm Hell.

**Comment by Warmuser** [comment]
Ok, thank you. I will explain the problem also there. Thanks anyway for the support! :)

**Comment by nfk** [comment]
Hi, I am also a Fedora user, I have pushed a short change about fedora dependencies after to have built bookworm on my fedora 27.  If necessary I can write the rpm spec file or trying to use CPack to create the rpm.

**Comment by babluboy** [comment]
Closing this issue as we have the Fedora installation covered on [bookworm website](https://babluboy.github.io/bookworm/#install)
Thanks @nfk for #153
