### ISSUE TITLE
left, right arrows jumps between chapters, not pages

### ISSUE THREAD

**Issue by JanneM** [babluboy/bookworm#119]
Ubuntu 17.04. left and right arrows jumps between chapters. There seems to be no shortcut to paginate forward and backward. Makes the application unusable.

**Comment by babluboy** [comment]
@JanneM Bookworm paginates by chapters currently and hence the scroll bar to scroll vertically for the contents of a chapter. There is a slider to quickly jump between chapters quickly and there are buttons to click forward/backward for chapter navigation (left/right arrow keys are the shortcuts)

Were you expecting in-chapter navigation rather than scrolling?

**Comment by JanneM** [comment]
I expected the arrow keys to jump forward and backward by displayed page, just like, say, Evince.  There's also no clickable areas near the left and and right edges to jump by page. It's really hopeless to try to read an ebook by scrolling forward line by line with the vertical arrow keys.

**Comment by babluboy** [comment]
Thats weird, can you please attach a screen shot of how Bookworm looks like on your system.
On Elementary OS the arrow keys and the forward and reverse icons on the footer move the pages backward and forward as in this screen shot:
https://raw.githubusercontent.com/babluboy/bookworm/gh-pages/images/BookwormReadingView.png[https://raw.githubusercontent.com/babluboy/bookworm/gh-pages/images/BookwormReadingView.png](url)

Based on this [post](http://www.omgubuntu.co.uk/2017/07/best-ebook-reader-app-ubuntu) I also thought it works the same on Ubuntu:
http://www.omgubuntu.co.uk/wp-content/uploads/2017/07/bookworm-ebook-app-on-ubuntu.jpg[http://www.omgubuntu.co.uk/wp-content/uploads/2017/07/bookworm-ebook-app-on-ubuntu.jpg](url)

**Comment by JanneM** [comment]
It looks correct; I don't think my version is broken. I didn't realize that viewing by page isn't implemented. This is not a bug at all, in other words.

Problem with touch screens right now (and unrelated to Bookworm of course) is that Gnome at least doesn't seem to have one-finger scrolling implemented. There's no way to actually scroll using the touch screen in other words, other than trying to grab and move the scroll bar a tiny amount at a time. 

With left-side and right-side clickable areas over the text that jump forward and back by page, or page flipping buttons it would work, but as you say, you don't yet have pagination so that won't really work.

Thank you for your work on this! I'll just close this since it's not really a bug.

**Comment by babluboy** [comment]
@JanneM Thanks for your response. I will come around to pagination sometime in the future. If possible, would you be able to post a screen shot of how bookworm looks like on touch screens...

**Comment by JanneM** [comment]
Here's the screenshot:

![bookworktouch](https://user-images.githubusercontent.com/702873/30001924-a6148a78-90d7-11e7-8637-4094347186d2.png)

As you can see, it looks the same.

I did notice that one-finger scrolling, where you scroll by simply dragging your finger on the screen, sort of works with Bookworm for some reason. But it's completely "dampened" - it follows your finger exactly, with no momentum at all, so it's very difficult to use. Compare it with, say, your phone, where you can "flick" to scroll up and down since the page has momentum that keeps it moving after you release the finger from the screen.

**Comment by babluboy** [comment]
Many thanks for the screen shot - the buttons dont look as good as on elementary OS though :-) especially the return button which is styled to be like an arrow pointing backwards as in the elementary os screen shot [here](https://raw.githubusercontent.com/babluboy/bookworm/gh-pages/images/TwoPageView.png)...the borders around the buttons also don't look so nice...

I can understand the issue with momentum, hopefully that improves with the implementation of webkit/gtk for touchscreens..

**Comment by TylerRick** [comment]
I just tried this out (on Ubuntu Budgie 17.04) while looking for an eBook reader and found the arrow keys navigating chapters instead of pages confusing and surprising too. Took me a while to even figure out that it was navigating chapters instead of pages (assumed the slider at the bottom was showing what page number I was on, not which chapter number).  Fortunately discovered Page Up / Page Down / Space can be used to change pages so I guess I'll get used to it.... :)

**Comment by repsorp** [comment]
Shortcuts should be corrected here:
https://babluboy.github.io/bookworm/#shortcuts

Bookworm has the following shortcuts
Reading View | Left and Right Arrow | Previous and Next page navigation

should be:
Reading View | Left and Right Arrow | Previous and Next chapter navigation

**Comment by babluboy** [comment]
@repsorp Thanks for the pointer. The navigation is based on the physical split of the book contents. For ePubs and Mobi they are usually chapters and for PDFs it is the individual pages. Although I have seen ePubs where there are a couple of chapters on a single content file (so navigation may partly be true)

I should probably just re-phrase the shortcut wording as:
Reading View | Left and Right Arrow | Previous and Next navigation

Does that seem correct in your opinion ?

**Comment by repsorp** [comment]
Previous and Next screen navigation ?

**Comment by babluboy** [comment]
@repsorp Done. Updated to "Previous and Next screen navigation" as per your suggestion.

**Comment by repsorp** [comment]
Probably not the best suggestion but it could remove ambiguity about the chapter/page navigation.
Thanks babluboy
Keep up the good work

**Comment by babluboy** [comment]
@repsorp No probs. Converting the book into pages that fit the viewport is my key target and being tracked by Issue #170
