### ISSUE TITLE
Add a progress bar under each book

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#12]
In the library view, add a progress bar under each book to show the read progress

**Comment by babluboy** [comment]
Adding a progress bar under each book will make the library view very busy...I'm thinking of adding a progress bar either on mouse over or better when the book is right clicked and a menu like "info" is selected...

**Comment by m-delvalle** [comment]
on hover ('ala Youtube') would be nice :)

**Comment by h4ck3r9** [comment]
What about a thin bar across the bottom of the book title? Something 3-4 pixels tall? It would be very simple, yet serve a great purpose. Doing it on hover would reduce the busy-ness of the whole task. I'm going to dive in and figure out if I can contribute at all.

**Comment by babluboy** [comment]
@h43k3r9 good suggestion ...I was thinking on the same lines...I will try to cover this feature in the current version I'm working on....

**Comment by babluboy** [comment]
Hacked a bit to add a progress bar to the book cover on mouse over.

![screenshot from 2017-07-13 21 16 10](https://user-images.githubusercontent.com/14061478/28186506-4cdb7fc6-6813-11e7-870c-1178ccff7c0c.png)
