### ISSUE TITLE
Black borders around grid view when scrollbars are displayed

### ISSUE THREAD

**Issue by Null-Senpai** [babluboy/bookworm#121]
Bookwork shows a black border when using the grid view _and_ you have more books then there is space on your screen causing scrollbars to be used. This issue disappears if I resize the window to make it large enough so the scrollbars disappear, or I remove some books from my library (which would also cause the scrollbars to disappear).

Terminal output when running `bookworm`: https://hastebin.com/tudamuxuni.pas

I am using GNOME Shell v. 3.24.2 on Antergos.
This also occurs when using the default *Adwaita* theme
![black](https://user-images.githubusercontent.com/13616397/29997413-6fbe862c-900a-11e7-9ca6-08a2aa0833ee.png)

**Comment by babluboy** [comment]
I guess this is a theme issue. Did you turn on the dark theme in the Bookworm preferences ? I wonder why the grid background is not being dark which is why it looks like a dark border. This is how Bookworm looks like on Elementary when I turn on Dark Mode in the preferences...

![screenshot from 2017-09-02 21 22 40](https://user-images.githubusercontent.com/14061478/29998546-c85f7ae6-9025-11e7-9382-c888ed9cd6d0.png)

**Comment by Null-Senpai** [comment]
Oh yeah, I did try toggling dark mode (in fact I had it in light mode, I just forgot to undo it). I am not sure if it is a theme thing, since the default Adwaita theme also causes this. If you want, I can try installing whatever theme elementary OS ships with?

**Comment by babluboy** [comment]
I saw that I was setting a border width on the Gtk.Grid which is probably why the black border was showing. This is how it looks like if I set the border to zero. But not sure if it looks good without the borders on the left and top...the scroll bar also comes overlay on the covers on the right...let me know what you think...

![screenshot from 2017-09-04 22 50 21](https://user-images.githubusercontent.com/14061478/30039060-dfc5be4e-91c3-11e7-89a5-7181b31323a1.png)

**Comment by ckrzen** [comment]
I like the black border. I also use the 'Adwaita-dark' GTK theme, though.

**Comment by babluboy** [comment]
I think I have fixed the issue which will remove the black border around the grid, but will still have a border. I have just shifted the border from the container Gtk.Grid to the individual EventBox cover images. The latest code is on GH (if building from source) or on the daily PPA (ppa:bablu-boy/bookworm-daily)...will be great if you can check on your system to see how it looks...here are screenshots from elementary in the light and dark modes...

![screenshot from 2017-09-05 09 03 40](https://user-images.githubusercontent.com/14061478/30052455-6905e22a-921d-11e7-83a8-dcb10b955bb7.png)
![screenshot from 2017-09-05 09 03 10](https://user-images.githubusercontent.com/14061478/30052456-69075290-921d-11e7-948b-ef08fda65a12.png)

**Comment by ckrzen** [comment]
Looks great.

**Comment by Null-Senpai** [comment]
Yeah, everything looks as it should now. Thanks for fixing it :slightly_smiling_face:
