### ISSUE TITLE
cmake error... i think

### ISSUE THREAD

**Issue by jmh1106** [babluboy/bookworm#131]
Hi
I am a completely new to all of this, have just installed Lubuntu on an old laptop to set up for the kids homeschooling. I wanted a reader so found this but i get stuck at 

cmake -DCMAKE_INSTALL_PREFIX=/usr ../
make
sudo make install

when I put the first line it sarts well but then gets stuck

-- Checking for modules 'gtk+-3.0;gee-0.8;granite;webkit2gtk-4.0>=2.16.0;sqlite3>=3.5.9;poppler-glib'
--   No package 'gee-0.8' found
--   No package 'granite' found
CMake Error at /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:415 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.7/Modules/FindPkgConfig.cmake:588 (_pkg_check_modules_internal)
  CMakeLists.txt:57 (pkg_check_modules)

-- Configuring incomplete, errors occurred!
See also "/home/hardy/bookworm/build/bookworm/build/CMakeFiles/CMakeOutput.log".

Clearly I am missing something but am not sure what exactly, any help appreciated? Also I can't seem to find the log mentioned in the last line?

**Comment by babluboy** [comment]
Thanks a lot for your interest in bookworm...what version of Ubuntu are you running...Bookworm will work for Xenial and above ...looks like you are missing some packages like granite on your system...

Looks like you are trying to build from source. First try installing from the PPA so you would automatically get updates, if that does not work I will help you in building from source.

Run these commands for installing from the stable PPA:


sudo add-apt-repository ppa:bookworm-team/bookworm
sudo apt-get update
sudo apt-get install bookworm

**Comment by babluboy** [comment]
@jmh1106 assuming the ppa method has worked. closing the issue. please get back if you still face probs

**Comment by jmh1106** [comment]
Apologies I haven't had chabcebto get back to the computer since I asked. I
am using lubuntu and had already ran the previous commands (which from
memory included yhe PPA) it just got stuck at the part I posted. Shoukd i
run them agaon from the start? Thanks



On 26/10/2017 11:34, "Siddhartha Das" <notifications@github.com> wrote:

@jmh1106 <https://github.com/jmh1106> assuming the ppa method has worked.
closing the issue. please get back if you still face probs

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/babluboy/bookworm/issues/131#issuecomment-339494833>,
or mute the thread

**Comment by babluboy** [comment]
@jmh1106 The commands you had mentioned first are trying to build from source. Please run the ```
following three commands and let me know what errors you are facing.
sudo add-apt-repository ppa:bookworm-team/bookworm
sudo apt-get update
sudo apt-get install bookworm
```
If you find errors, do report them here and also the output of the following command so that I know what version of lubuntu you are running:
`cat /etc/*release`
