### ISSUE TITLE
Flatpak for Bookworm

### ISSUE THREAD

**Issue by BharatKalluri** [babluboy/bookworm#132]
Hello @babluboy!

I made a[ flatpak repo](https://github.com/BharatKalluri/bookworm-flatpak) for bookworm and it seems to work fine for me. However Please install and check if all features are working fine. Once that is done, we can upload it to [flathub](http://flathub.org/).

If all the features work, ping me. Then you can close this issue :-)

**Comment by babluboy** [comment]
@BharatKalluri Installed flatpak from the PPA on elementary OS Loki (Ubuntu 16.04.3 LTS/Linux 4.4.0-97-generic):
```
sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak
```

Then tried following your install instructions, but getting the following error on executing the first line:
```
flatpak build-init com.github.babluboy.bookworm com.github.babluboy.bookworm org.gnome.Sdk org.gnome.Platform 3.24
error: org.gnome.Sdk 3.24 not installed

```
Am I missing a step or install ?

**Comment by BharatKalluri** [comment]
Yeah, install flathub 
```flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo```

and then
```flatpak install flathub org.gnome.Sdk 3.24```.

If its still not working for you, ping me on [Gitter](gitter.im). Hope you are using gitter :-)

**Comment by babluboy** [comment]
Getting stuck after install of flathub:
```
sid@sid-Latitude-E4300:~/Documents/Projects/bookworm$ flatpak install flathub org.gnome.Sdk//3.24
org.gnome.Sdk/x86_64/3.24 already installed, skipping
sid@sid-Latitude-E4300:~/Documents/Projects/bookworm$ flatpak build-init com.github.babluboy.bookworm com.github.babluboy.bookworm org.gnome.Sdk org.gnome.Platform 3.24
error: org.gnome.Platform 3.24 not installed
```

**Comment by BharatKalluri** [comment]
Yeah, sorry for the late reply @babluboy . Replied on gitter.

**Comment by babluboy** [comment]
@BharatKalluri Including the command here which worked:
`flatpak install flathub org.gnome.Platform 3.24`

With the above, I was able to make the first instruction work i.e.:
`flatpak build-init com.github.babluboy.bookworm com.github.babluboy.bookworm org.gnome.Sdk org.gnome.Platform 3.24`

Now, I'm stuck on the second command:
`flatpak-builder --repo=repo com.github.babluboy.bookworm com.github.babluboy.bookworm.json --force-clean`
Its giving me an error: `flatpak-builder: command not found`

**Comment by BharatKalluri** [comment]
@babluboy ,Seems like you need to make install flatpak-builder. follow the instructions from here https://github.com/flatpak/flatpak-builder.\

I use fedora, it seems like everything is already set up in fedora.

**Comment by babluboy** [comment]
@BharatKalluri after I installed flatpak-builder from the ppa, I was able to download the `com.github.babluboy.bookworm.json` file from your repository and run the command in the same dir where the json was downloaded:
`flatpak-builder --repo=repo com.github.babluboy.bookworm com.github.babluboy.bookworm.json --force-clean`

However, after running for some time this ended with the following error:
```
Resolving deltas: 100% (2211/2211), done.
Checking connectivity... done.
Failed to download sources: module bookworm: Can't find file at bookworm-app.patch
```

**Comment by BharatKalluri** [comment]
Hmm, that should not happen. Anyways, I updated the repo. Try it and tell me if anything is wrong. :-)

**Comment by babluboy** [comment]
@BharatKalluri Sucess !! I downloaded the modified bookworm-app.patch to my local directory where the com.github.babluboy.bookworm.json was present and the build and install succeeded.

On running bookworm from flatpak, everything works fine except a couple of issues I noticed:
1- The buttons for the profile were not having the correct background colors
2- The return button is not arrow shaped (elementary CSS not applied - same prob in Ubuntu)
3- The auto discovery of books on watched folders did not work as "cron" does not work on flatpak (I plan to remove this dependency later and introduce a daemon)

Overall the functionality worked fine. So now we can discuss how to push this into flathub and then update it on every stable release. Perhaps the flatpak build and install can be added to the TravisCI to build the flatpak on every push to Github ?

![screenshot from 2017-10-18 22 02 20](https://user-images.githubusercontent.com/14061478/31742619-0c38a758-b450-11e7-8722-133d553193be.png)

**Comment by babluboy** [comment]
Noting down the steps which I followed to complete the flatpak built and installed on elementary OS Loki (Ubuntu 16.04.3 LTS/Linux 4.4.0-97-generic):

1. Install flatpak and flatpack-builder
```
sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak flatpak-builder
```
2. Created a directory "myflatpak" and downloaded the com.github.babluboy.bookworm.json and bookworm-app.patch from your repository [here](https://github.com/BharatKalluri/bookworm-flatpak)

3. Changed to the "myflatpak" directory and ran the following commands to install flathub and sdk
```
flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo
flatpak install flathub org.gnome.Platform 3.24
```

4. From the "myflatpak" directory the following commands were executed:
```
flatpak build-init com.github.babluboy.bookworm com.github.babluboy.bookworm org.gnome.Sdk org.gnome.Platform 3.24
flatpak-builder --repo=repo com.github.babluboy.bookworm com.github.babluboy.bookworm.json --force-clean
# Press y when asked
flatpak build-finish com.github.babluboy.bookworm
flatpak build-export repo com.github.babluboy.bookworm
flatpak --user remote-add --no-gpg-verify --if-not-exists bookworm-repo repo
flatpak --user install bookworm-repo com.github.babluboy.bookworm
flatpak run com.github.babluboy.bookworm
```

**Comment by babluboy** [comment]
@BharatKalluri Quick question - what is the significance of the bookworm-app.patch file. Is there a problem with the [constants.vala](https://github.com/BharatKalluri/bookworm-flatpak/blob/master/bookworm-app.patch) which it is trying to solve ? Can we fix the constants.vala and remove the need for this patch file ?

**Comment by BharatKalluri** [comment]
@babluboy  In the constants.vala file, All the paths have been hardcoded. Flatpak creates a virtual sandbox to run applications so that the applications need not have access

 to the file system of the user. So it has its own virtual file system.

When the application is trying to access the /usr directory in the user's system. Since flatpak does not have a /usr directory, it will cause an error. So I had to path all /usr to /app to make the application fit into the flatpak system.

To remove the patch, The program should take the /usr directory from the user. During the compile and run stage, the user actually does give you the path, In ```cmake -DCMAKE_INSTALL_PREFIX=/usr ../```. If that can be used to replace /usr in constants.vala, then the patch file is not needed!

**Comment by babluboy** [comment]
@BharatKalluri Many thanks for explaining it so clearly. I can think of two ways now:
1- set the installation path during the install in a config file on the app's config directory i.e. ~/.config/bookworm/installpath.txt and use that during run time
2- grab the path install prefix from the CMakeLists.txt on the first run and set it in the app's config and use that (but what if the install files are removed after installation or require higher permissions to read ?) 
3- locate the path by doing a search for one of the app's resources (not a good way as permissions might block the search from finding the resource)

However, I would like to do some research on how this should be done in a more elegant way. elementary apps are moving to flatpak/snaps so there might be some thought in this regard. Will check in the forum

**Comment by babluboy** [comment]
@BharatKalluri I have got a response on how to achieve this on this [G+ post](https://plus.google.com/108373005915819607337/posts/4AxbnVNckC4?fscid=z12ewttqeyakdjysm22itrvx0lrwjvoj004.1508587316310954). Will use the configure_file directive and if that works then we can remove the patch file.

**Comment by babluboy** [comment]
Made the install dynamic with the use of configure_file directive in [CMakeLists](https://github.com/babluboy/bookworm/blob/756501973cb58087205d196d38ff11e97409fbb7/CMakeLists.txt#L28)

Used the dynamic tag in [constants](https://github.com/babluboy/bookworm/blob/756501973cb58087205d196d38ff11e97409fbb7/src/constants.vala#L140) for setting the path to the icons, scripts, etc

The above successfully installs bookworm to the /app directory and refers the installed icons, scripts, etc from the same instead of the earlier hardcoded /usr directory. This removes the necessity of a patch. Have requested a [PR on flathub](https://github.com/flathub/flathub/pull/138) here for bookworm. 

Closing this issue - but feel free to add any further comments here

**Comment by babluboy** [comment]
@BharatKalluri Hi, will be great if you can have a look at the two questions raised by Richards on the bookworm flatpak json script:
[https://github.com/flathub/flathub/pull/138#discussion_r148321207](https://github.com/flathub/flathub/pull/138#discussion_r148321207)

**Comment by GogoAkira** [comment]
Well I guess these comments are old, but flatpak still tries to install Gnome and I'm running debian minimal with bspwm.
