### ISSUE TITLE
Issue with python version

### ISSUE THREAD

**Issue by BasioMeusPuga** [babluboy/bookworm#134]
Hello,

I installed bookworm from the aur. 
The python modules installed in `/opt/bookworm/mobi_lib` use `/usr/bin/env python`. Unfortunately, this makes it impossible to add mobi files in any distro using python 3 as its default.

Additionally, I was able to add mobi files by switching the line to `/usr/bin/env python2`.

**Comment by babluboy** [comment]
@BasioMeusPuga Many thanks for raising this. I was not aware of this issue with python 3. Need to find a way to have a conditional way to use the /usr/bin/env line based on the python version. That way it will work with all versions of python

Please suggest if you have any ideas on this.

**Comment by malcolmlewis** [comment]
Hi
FWIW in openSUSE it's /usr/bin/python this then softlinks to either python2.x or python3.x as required. So I actually remove the /usr/bin/env as this is considered a packaging error and replace...

https://build.opensuse.org/package/view_file/Publishing/bookworm/bookworm.spec?expand=1

**Comment by babluboy** [comment]
@BasioMeusPuga I saw this hack [here](https://askubuntu.com/questions/817255/default-to-python3-for-usr-bin-env-python) to make scripts work with both python and python3
```
#!/bin/sh
''''which python3 >/dev/null 2>&1 && exec python3 "$0" "$@" # '''
''''which python  >/dev/null 2>&1 && exec python  "$0" "$@" # '''
''''exec echo "Error: I can't find python anywhere"         # '''
```
It will be great if you can replace the shebang on all the py files in the mobi_lib directory with the above to see if it correctly picks up python3 on your system. 

I will make the changes if it works on your system as I have tried and checked it works on elementary OS Loki.

**Comment by BasioMeusPuga** [comment]
Hello.

I complied the latest git revision, and I replaced the shebang in every python module (now in `/usr/share/bookwork/scripts/`). Unfortunately, I'm getting this:

    utils.vala:106: Error encountered in execution of sync command [/usr/share/bookworm/scripts/mobi_lib/mobi_unpack.py "/home/bmp/Downloads/Metamorphosis-jackson.mobi" "/home/bmp/.config/bookworm/books/Metamorphosis-jackson.mobi/"]:   File "/usr/share/bookworm/scripts/mobi_lib/mobi_unpack.py", line 262    print "Mobi Version: ", self.version                         ^SyntaxError: Missing parentheses in call to 'print'. Did you mean print(print "Mobi Version: ", self.version)?

I believe this is the same error as before. 

May I direct your attention to this PEP? https://www.python.org/dev/peps/pep-0394/#id14
They state that using `/usr/bin/env python2` for a script that is explicitly incompatible with Python 3 is the conventional way of doing things.

**Comment by babluboy** [comment]
@BasioMeusPuga Many thanks for your testing. I also got the same issue on elementary OS by changing the shebang to `/usr/bin/env python3`. This proves that the scripts are only compatible with python2. Based on the sensible suggestion in the PEP you reference above, I have changed the shebang of all the mobi python scripts to state `/usr/bin/env python2`. Just pushed the changes to master branch

Hopefully this should pick up python2 to execute the scripts and avoid the issue with python3. I should in the future make the scripts python3 compatible or replace the python scripts with equivalent vala code. Closing this issue, please feel free to re-open in case of further issues.
