### ISSUE TITLE
OpenSUSE Build - Packaging errors file permissions and icon sizes

### ISSUE THREAD

**Issue by malcolmlewis** [babluboy/bookworm#137]
Hi
I've packaged up bookworm on the openSUSE Build Service with a view to pushing into the distribution. Is it possible to fix the following issues?

The AUTHORS and COPYING files have the wrong permissions and not sure about com.github.babluboy.bookworm.htmlscripts.txt all are 0755 can this be changed to 0644?

The second part of the report is about the icon sizes, can these be re-sized to the correct dimensions for the hicolor file locations?

[   43s] RPMLINT report:
[   43s] ===============
[   45s] bookworm.x86_64: W: script-without-shebang /usr/share/bookworm/scripts/tasks/com.github.babluboy.bookworm.htmlscripts.txt
[   45s] This text file has executable bits set or is located in a path dedicated for
[   45s] executables, but lacks a shebang and cannot thus be executed.  If the file is
[   45s] meant to be an executable script, add the shebang, otherwise remove the
[   45s] executable bits or move the file elsewhere.
[   45s] 
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/16x16/actions/bookworm_rating_2.png expected: 16x16 actual: 32x16
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/16x16/actions/bookworm_rating_3.png expected: 16x16 actual: 48x16
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/16x16/actions/bookworm_rating_4.png expected: 16x16 actual: 64x16
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/16x16/actions/bookworm_rating_5.png expected: 16x16 actual: 80x16
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-1.png expected: 256x256 actual: 412x616
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-2.png expected: 256x256 actual: 412x616
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-3.png expected: 256x256 actual: 412x616
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-4.png expected: 256x256 actual: 412x616
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-5.png expected: 256x256 actual: 412x616
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-placeholder-cover.png expected: 256x256 actual: 412x616
[   45s] bookworm.x86_64: W: wrong-icon-size /usr/share/icons/hicolor/128x128/apps/bookworm.png expected: 128x128 actual: 64x64
[   45s] Your icon file is installed in a fixed-size directory, but has a largely
[   45s] incorrect size. Some desktop environments (e.g. GNOME) display them
[   45s] incorrectly.

**Comment by babluboy** [comment]
@malcolmlewis Many thanks for your interest in Bookworm and helping to get it on the opensuse distro.
Will look into the permissions issues and also on the icon size issue which appears strange as I had scaled the icons with gimp to the specified sizes.

**Comment by paulcarroty** [comment]
@babluboy please also add the [URL](https://build.opensuse.org/package/show/Publishing/bookworm) in [README](https://github.com/babluboy/bookworm/blob/master/README.md#how-to-install-bookworm).

**Comment by malcolmlewis** [comment]
Hi
If a link is added, better to use;
https://software.opensuse.org/package/bookworm

Then a end user will get to the correct location for either the development or (when it gets into a release) the released version.

**Comment by babluboy** [comment]
Made the following changes:
1- Removed the execute permissions on the html script (read is sufficient)
`-r-----r-- 1 root root 5714 Nov  3 22:02 /usr/share/bookworm/scripts/tasks/com.github.babluboy.bookworm.htmlscripts.txt`

2. Added the link [https://software.opensuse.org/package/bookworm](https://software.opensuse.org/package/bookworm) to the install section on the bookworm website : [https://babluboy.github.io/bookworm/#install](https://babluboy.github.io/bookworm/#install)

3. Updated the permissions on AUTHORS, CODE_OF_CONDUCT.md, COPYING, LICENSE to read only (-r--r--r--)

4. All the mobi python scripts now have the shebang which specify: `#!/usr/bin/env python2`

Let me know if this takes care of the key issues on OpenSUSE (apart from the icon size issues)

**Comment by malcolmlewis** [comment]
Hi
Perfect, all looks good now except the icon sizes as you indicated.

Many thanks for the link too :)

**Comment by babluboy** [comment]
The icon sizes is also causing an error on the Flathub website: https://github.com/flathub/com.github.babluboy.bookworm/issues/3

**Comment by babluboy** [comment]
@malcolmlewis The icons have been re-designed and the correct sizes are now available in the master branch. Can you please try the build again to confirm if the icon size issues are resolved. Please re-open if the issue persists.

Note: With the last release the binary/executable for bookworm has changed to com.github.babluboy.bookworm to follow the RDNN naming guidelines. Hopefully this should not cause issues for the OpenSUSE build.
