### ISSUE TITLE
Bookworm for Ubuntu 17.10?

### ISSUE THREAD

**Issue by murshid1988** [babluboy/bookworm#138]
Any timeline for Ubuntu 17.10 release?

**Comment by babluboy** [comment]
@murshid1988 I have got the daily PPA built on 17.10 (Artful) on launchpad...let me do the stable PPA build on launchpad and update back

**Comment by murshid1988** [comment]
Cool. Please update once you have done it :)

**Comment by babluboy** [comment]
@murshid1988 I have now got both the stable and the daily PPAs available for Artful(Ubuntu 17.10)
stable PPA: `sudo add-apt-repository ppa:bookworm-team/bookworm`
daily (unstable) PPA: `sudo add-apt-repository ppa:bablu-boy/bookworm-daily`

Please re-open this in case of problems in installing bookworm on 17.10

**Comment by murshid1988** [comment]
I have received an unmet dependency issue. Should open a new issue?

**Comment by babluboy** [comment]
@murshid1988 Please provide the details of the issue you see on the command line so that I can figure out which of the dependent libraries are you missing. A usual suspect is the granite or the webkit library.

I got Bookworm to build on Artful on launchpad by including the elementary daily ppa:
sudo add-apt-repository ppa:elementary-os/daily
sudo apt-get update

**Comment by murshid1988** [comment]
> The following packages have unmet dependencies:
>  bookworm : Depends: libgranite3 (>= 0.2.0) but it is not installable
> E: Unable to correct problems, you have held broken packages.

**Comment by murshid1988** [comment]
Daily build gets installed though...

**Comment by babluboy** [comment]
@murshid1988 You would need to add this PPA to resolve this issue: ppa:elementary-os/daily
My other application had this issue and this was the same resolution: [link](https://answers.launchpad.net/nutty/+question/402887)

If you like to have the stable one:
1. uninstall and remove the daily ppa
2. add the eos ppa
```
sudo add-apt-repository ppa:elementary-os/daily
sudo apt-get update
```
3. And then add the stable PPA and install bookworm

Otherwise, you can use the daily build until I move it to the stable ppa

**Comment by sanderjo** [comment]
FWIW:

Ubuntu 17.10 (fully updated) here:
1) ppa:bablu-boy/bookworm-daily did not work; libgranite error.
2) the trick with uninstall & elementary-os & install did not work either
3) ppa:bablu-boy/bookworm-daily does work. :+1:

**Comment by babluboy** [comment]
@sanderjo 
> ppa:bablu-boy/bookworm-daily did not work; libgranite error.
Did you mean ppa:bookworm-team/bookworm ?

**Comment by sanderjo** [comment]
> Did you mean ppa:bookworm-team/bookworm did not work ?

Oops. Yes. Sorry.

**Comment by tudoanh** [comment]
@sanderjo Sadly that `ppa:bablu-boy/bookworm-daily` did not work on my Ubuntu 17.10 :(  
```
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 bookworm : Depends: com.github.babluboy.bookworm but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```

**Comment by babluboy** [comment]
@tudoanh Can you try the following two methods:

Method 1:
```
sudo add-apt-repository ppa:bookworm-team/bookworm
sudo add-apt-repository ppa:elementary-os/stable
sudo apt-get update
sudo apt-get install com.github.babluboy.bookworm
```
If the above method is successful, then you can remove the elementary PPA after bookworm is installed

Method 2: Installation with Flatpak:
```
sudo add-apt-repository ppa:alexlarsson/flatpak
sudo apt update
sudo apt install flatpak
flatpak install --from https://flathub.org/repo/appstream/com.github.babluboy.bookworm.flatpakref
```
Will be great to know how it goes - and a screen shot on Ubuntu 17.10 if you are successful. :-)

**Comment by MohamedMIB** [comment]
about the first Method this is what i got : 
 add-apt-repository ppa:elementary-os/stable
 
 More info: https://launchpad.net/~elementary-os/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

gpg: keybox '/tmp/tmp9_q2_pip/pubring.gpg' created
gpg: connecting dirmngr at '/tmp/tmp9_q2_pip/S.dirmngr' failed: IPC connect call failed
gpg: keyserver receive failed: No dirmngr
Failed to add key.
![root root -home-root1_039](https://user-images.githubusercontent.com/33508969/36634889-956fabda-19a3-11e8-9703-38de109a620a.png)

**Comment by babluboy** [comment]
@MohamedMIB Thanks for the update. The error you got on the first method looks a GPG Key issue and some solution is mentioned [here](https://unix.stackexchange.com/questions/401547/gpg-keyserver-receive-failed-no-dirmngr/401548)

But good that the second method using Flatpak  worked. The screenshot  you have provided about the Drupal book is another ebook reader ? Does not look like Bookworm

**Comment by dehuszar** [comment]
For me running `sudo add-apt-repository ppa:bookworm-team/bookworm && sudo apt update` and then installing from the Software Manager in Ubuntu 17.10 installs, but then running gives me the error:
```
$ sudo bookworm
mkdir: cannot create directory '/run/user/0': Permission denied
[INFO 14:43:20.438842] Application.vala:154: Bookworm version: (null)
[INFO 14:43:20.438932] Application.vala:156: Kernel version: 4.13.0-39-generic
[WARNING 14:43:20.439278] [Gtk] Locale not supported by C library.	Using the fallback 'C' locale.
No protocol specified
Failed to connect to Mir: Failed to connect to server socket: No such file or directory
Unable to init server: Could not connect: Connection refused
[WARNING 14:43:20.442651] [Gtk] cannot open display: :0
```

I'm guessing that's because Mir isn't a part of Ubuntu anymore

**Comment by babluboy** [comment]
Googled this a bit, and looks like this is due to the DISPLAY not being set. Can you check this to have the display set and see if it resolves:
https://askubuntu.com/questions/871092/failed-to-connect-to-mir-failed-to-connect-to-server-socket-no-such-file-or-di?utm_medium=organic&utm_source=google_rich_qa&utm_campaign=google_rich_qa

**Comment by dehuszar** [comment]
Didn't make a difference for me.  I think the underlying issue may be that Ubuntu no longer ships with Mir.
