### ISSUE TITLE
Use "starred" and "non-starred" instead of "help-about" and "help-about-symbolic"

### ISSUE THREAD

**Issue by filipkemuel** [babluboy/bookworm#139]
I really wonder why You chose "help-about" and "help-about-symbolic" for the rating icons. 
Granted in the elementary icon-theme these are represented by stars. But in almost all other icon-themes they are represented by an exclamation mark or question mark.

And most themes actually include "starred" and "non-starred" icons... even the Elementary icon-theme!
https://github.com/elementary/icons/blob/master/status/16/starred.svg
https://github.com/elementary/icons/blob/master/status/16/non-starred.svg

So by using that you would make Bookworm integrate a little better between different distro's and icon-themes.

**Comment by babluboy** [comment]
@filipkemuel Thanks for raising this issue. I had also seen a screen shot of Ubuntu where the stars appeared as circles and questions. 

On elementary OS I was searching for the "starred" and "non-starred" icons and could not locate it on the /usr/share/icons/elementary/actions/16/ folder. "help-about" and "help-about-symbolic" were the nearest I could find.

Just changed the icons names and everything is working fine on eOS Loki - pushed to GH and will release as part of next release v1.0

Thanks again for helping make Bookworm better :-)
