### ISSUE TITLE
Go directly to the word when cliking on a search result

### ISSUE THREAD

**Issue by forteller** [babluboy/bookworm#145]
When searching for a word and clicking a search result I'm sent to the start of the chapter, not the place in the chapter where the word appears. This makes the search feature quite useless, and I've had to install another, otherwise worse e-book reader, just to find the context of a word. I'd like to only have to use Bookworm :) 

Thank you for your great work!

**Comment by babluboy** [comment]
@forteller I recognized the issue and had put up issue #103 for the same.
This feature is now completed and will soon be available when I push the 1.0 changes to AppCenter.

If you want to use this right away, then you can use the daily build - however, its not stable and you might face issues as I push daily changes into the same. If you are still interested, then you can get the daily build by either building from source or from the daily PPA (ppa:bablu-boy/bookworm-daily)
