### ISSUE TITLE
Build on openSUSE

### ISSUE THREAD

**Issue by awissu** [babluboy/bookworm#148]
Hi!
I want to inform you about the found problems when building RPM:

> bookworm.i586: W: script-without-shebang /usr/share/bookworm/scripts/tasks/com.github.babluboy.bookworm.htmlscripts.txt
> [   99s] This text file has executable bits set or is located in a path dedicated for
> [   99s] executables, but lacks a shebang and cannot thus be executed.  If the file is
> [   99s] meant to be an executable script, add the shebang, otherwise remove the
> [   99s] executable bits or move the file elsewhere.
> ...
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/16x16/actions/bookworm_rating_2.png expected: 16x16 actual: 32x16
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/16x16/actions/bookworm_rating_3.png expected: 16x16 actual: 48x16
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/16x16/actions/bookworm_rating_4.png expected: 16x16 actual: 64x16
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/16x16/actions/bookworm_rating_5.png expected: 16x16 actual: 80x16
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-1.png expected: 256x256 actual: 412x616
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-2.png expected: 256x256 actual: 412x616
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-3.png expected: 256x256 actual: 412x616
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-4.png expected: 256x256 actual: 412x616
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-default-cover-5.png expected: 256x256 actual: 412x616
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/bookworm/icons/hicolor/256x256/apps/bookworm-placeholder-cover.png expected: 256x256 actual: 412x616
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/icons/hicolor/128x128/apps/bookworm.png expected: 128x128 actual: 64x64
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/icons/hicolor/16x16/apps/bookworm.png expected: 16x16 actual: 64x64
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/icons/hicolor/24x24/apps/bookworm.png expected: 24x24 actual: 64x64
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/icons/hicolor/32x32/apps/bookworm.png expected: 32x32 actual: 64x64
> [   99s] bookworm.i586: W: wrong-icon-size /usr/share/icons/hicolor/48x48/apps/bookworm.png expected: 48x48 actual: 64x64
> [   99s] Your icon file is installed in a fixed-size directory, but has a largely
> [   99s] incorrect size. Some desktop environments (e.g. GNOME) display them
> [   99s] incorrectly.
> ...
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_dict.py /usr/bin/env python
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_html.py /bin/env python
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_index.py /usr/bin/env python
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_k8proc.py /usr/bin/env python
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_ncx.py /usr/bin/env python
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_opf.py /usr/bin/env python
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_split.py /usr/bin/env python
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_uncompress.py /usr/bin/env python
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_unpack.py /usr/bin/env python
> [   99s] bookworm.i586: E: env-script-interpreter (Badness: 9) /usr/share/bookworm/scripts/mobi_lib/mobi_utils.py /usr/bin/env python
> [   99s] This script uses 'env' as an interpreter. For the rpm runtime dependency
> [   99s] detection to work, the shebang #!/usr/bin/env python  needs to be patched into
> [   99s] #!/usr/bin/python  otherwise the package dependency generator merely adds a
> [   99s] dependency on /usr/bin/env rather than the actual interpreter /usr/bin/python.
> [   99s] Alternatively, if the file should not be executed, then ensure that it is not
> [   99s] marked as executable or don't install it in a path that is reserved for
> [   99s] executables.
> ...
> [   99s] bookworm.i586: E: executable-docs (Badness: 900) /usr/share/doc/packages/bookworm/AUTHORS
> [   99s] Documentation should not be executable.

**Comment by malcolmlewis** [comment]
Hi
See issue https://github.com/babluboy/bookworm/issues/137

I've already pushed to the Publishing repository;
https://build.opensuse.org/package/show/Publishing/bookworm

**Comment by babluboy** [comment]
Thanks - will close this issue and track via #137
