### ISSUE TITLE
File type specify on File picker dialog

### ISSUE THREAD

**Issue by choyan** [babluboy/bookworm#15]
As the application currently supports only the ePub format, I think it's better that the file picker to act like one. It will specifically show only ePub format files. Currently, there is an option available I can see in the dialog, to select only ePub files. But it is not working properly.

![screenshot from 2017-02-26 16 59 52](https://cloud.githubusercontent.com/assets/1283240/23339120/7c0815dc-fc45-11e6-9290-7d5531474b0f.jpeg)
![screenshot from 2017-02-26 17 00 01](https://cloud.githubusercontent.com/assets/1283240/23339121/81042508-fc45-11e6-8d39-1717ee6b4a7b.jpeg)

**Comment by babluboy** [comment]
@choyan Fixed the issue with the file filter and release it to PPA and Git. ePub should be the default one and should only show epub files in the folder. "All files" is also there in case the user wants to choose another file extension to open.Please check and re-open this if you see any issue with the implementation.

**Comment by choyan** [comment]
It's great. Working awesomely! And you're fast:D
