### ISSUE TITLE
Add a ChangeLog/NEWS file?

### ISSUE THREAD

**Issue by malcolmlewis** [babluboy/bookworm#150]
Hi
Is it possible to include a ChangeLog or NEWS file with a list of changes between releases? This will make it easier for packagers like me to use some automation to summarize after a release?

At present it means trolling through the commits and closed issues for bugs etc.

**Comment by babluboy** [comment]
The [appdata](https://github.com/babluboy/bookworm/blob/master/data/com.github.babluboy.bookworm.appdata.xml) file will have a list of changes under the `<releases>` tag for each release and this is currently used to show the change long in Appcenter....hopefully you can use the same.

example of the current release - i hope to make it better with more details in the next release.
```
<release version="0.9" date="2017-07-23">
      <description>
       <p>Support mobi format and UX improvements</p>
      </description>
</release>
```

**Comment by malcolmlewis** [comment]
Hi
That sounds perfect, can get that info out...

However, openSUSE have standards for referencing issues, for example my current changes file has;

  * Updated python scripts to indicate dependency on python2,
    (gh#babluboy/bookworm#134).
  * Updated star and non-star icons, (gh#babluboy/bookworm#139).
  * Added cmake prefix for install path to be set dynamically.
  * Fix python shebang, (gh#babluboy/bookworm/pull#135).
  * Add Viewer Desktop category, (gh#babluboy/bookworm/pull#136).
  * Translation updates.

Even if just an issue/pull number is referenced in a fix, then it makes it easier to update the package changes file?

**Comment by babluboy** [comment]
I mark all the issues with a Release tag and every issue that has changes associated with it will be tagged [1.0](https://github.com/babluboy/bookworm/milestone/9?closed=1) for the next release.
Will that help you for the level of details you are looking at.

**Comment by babluboy** [comment]
I will try and reference the issue number in subsequent fixed and PRs, so you can use the milestone link to co-relate all the fixes and PR with the issues.

**Comment by malcolmlewis** [comment]
Hi
Sure, that sounds perfect :)
