### ISSUE TITLE
Can't build in Ubuntu 16.04

### ISSUE THREAD

**Issue by deionut** [babluboy/bookworm#152]
I tried to follow the instructions in the readme to build & install on Ubuntu 16.04 but I get the following error when trying to run the make command:

/bookworm/src/window.vala:144.5-144.60: error: The name `set_allow_universal_access_from_file_urls' does not exist in the context of `WebKit.Settings'
    webkitSettings.set_allow_universal_access_from_file_urls(true); //this gives launchpad build error for Yaketty
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

**Comment by babluboy** [comment]
@deionut Have a look at Issue #94 - this issue has been raised and resolved. It looks like a version issue. See if you can update your Vala version.

Closing this issue as a duplicate - please add comments on #94 and we can work to resolve it there as necessary.
