### ISSUE TITLE
Install fails on Artful (17.10)

### ISSUE THREAD

**Issue by blindfish3** [babluboy/bookworm#159]
I tried to install under Ubuntu Budgie and got the libgranite failure that has been reported elsewhere:

> The following packages have unmet dependencies.
>  bookworm : Depends: libgranite3 (>= 0.2.0) but it is not installable

Rather than adding the Elementary PPAs as suggested in [#112](https://github.com/babluboy/bookworm/issues/112#issuecomment-322511535) I found a list of package files on [launchpad](https://launchpad.net/~elementary-os/+archive/ubuntu/stable/+sourcepub/5334729/+listing-archive-extra).

After installing `libgranite-common` and then `libgranite3` I was able to run `sudo apt install bookworm` successfully :)

**Comment by babluboy** [comment]
@blindfish3 many thanks for this...looks like a better way to get libgranite dependables...I will keep this issue open until I find some time to update the installation instruction section with the details provided...

**Comment by naafx8** [comment]
Try to build this library. https://github.com/elementary/granite
It'll gave you libgranite. Because ubuntu has no package for libgranite for artful if i'm not mistaken.
Hopes that help you.
oh, BTW, I'm using ubuntu 18.04 (bionic)

**Comment by babluboy** [comment]
The [website](https://babluboy.github.io/bookworm/#install) has been updated to reflect the issue of the missing libgranite package. While it would have been more accurate to mention the exact granite dependencies, it will be simpler and future proofed if the elementary stable ppa is added and then removed after installation - so I have mentioned the same on the website.

**Comment by amoghatr** [comment]
doesn't help. and BTW, bookworm downloaded from the Ubuntu Software centre doesn't launch. Seems like a very useful software, hope the issues with libgranite will be resolved.

**Comment by babluboy** [comment]
@amoghatr Which Ubuntu version are you running:
Can you please provide the output on running the following commands in sequence:
```
sudo add-apt-repository ppa:elementary-os/stable
sudo apt-get update
sudo add-apt-repository ppa:bookworm-team/bookworm
sudo apt-get update
sudo apt-get install com.github.babluboy.bookworm
```

**Comment by amoghatr** [comment]
I'm running 17.10. I managed to install it via flatpak by downgrading the repository via aptitude though.
well, here's the output :- 
``
$ sudo add-apt-repository ppa:elementary-os/stable
[sudo] password for amogha: 
 
 More info: https://launchpad.net/~elementary-os/+archive/ubuntu/stable
Press [ENTER] to continue or Ctrl-c to cancel adding it.

gpg: keybox '/tmp/tmpdzzz9zaf/pubring.gpg' created
gpg: /tmp/tmpdzzz9zaf/trustdb.gpg: trustdb created
gpg: key BF36996C4E1F8A59: public key "Launchpad PPA for elementary OS team" imported
gpg: Total number processed: 1
gpg:               imported: 1
OK

sudo apt-get update
Hit:1 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu artful InRelease
Hit:2 http://ppa.launchpad.net/bablu-boy/bookworm-daily/ubuntu artful InRelease
Hit:3 http://ppa.launchpad.net/bookworm-team/bookworm/ubuntu artful InRelease
Hit:4 http://ppa.launchpad.net/docky-core/stable/ubuntu artful InRelease 
Ign:5 http://ppa.launchpad.net/elementary-os/stable/ubuntu artful InRelease
Hit:6 http://ppa.launchpad.net/go-for-it-team/go-for-it-daily/ubuntu artful InRelease
Hit:7 http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu artful InRelease
Hit:8 http://ppa.launchpad.net/noobslab/icons/ubuntu artful InRelease    
Hit:9 http://ppa.launchpad.net/noobslab/macbuntu/ubuntu artful InRelease 
Hit:10 http://ppa.launchpad.net/noobslab/themes/ubuntu artful InRelease  
Hit:11 http://ppa.launchpad.net/papirus/papirus/ubuntu artful InRelease   
Err:12 http://ppa.launchpad.net/elementary-os/stable/ubuntu artful Release
  404  Not Found
Err:13 http://in.archive.ubuntu.com/ubuntu artful InRelease
  502  Connection timed out [IP: 2001:67c:1360:8001::17 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/elementary-os/stable/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.

$ sudo add-apt-repository ppa:bookworm-team/bookworm
 PPA for stable build of Bookworm
 More info: https://launchpad.net/~bookworm-team/+archive/ubuntu/bookworm
Press [ENTER] to continue or Ctrl-c to cancel adding it.

gpg: keybox '/tmp/tmpgpjxc8bt/pubring.gpg' created
gpg: /tmp/tmpgpjxc8bt/trustdb.gpg: trustdb created
gpg: key 01ECAA19EC33CA14: public key "Launchpad PPA for Bookworm-team" imported
gpg: Total number processed: 1
gpg:               imported: 1
OK
~$ sudo apt-get update
Hit:1 http://ppa.launchpad.net/alexlarsson/flatpak/ubuntu artful InRelease
Hit:2 http://ppa.launchpad.net/bablu-boy/bookworm-daily/ubuntu artful InRelease
Hit:3 http://ppa.launchpad.net/bookworm-team/bookworm/ubuntu artful InRelease
Hit:4 http://ppa.launchpad.net/docky-core/stable/ubuntu artful InRelease 
Ign:5 http://ppa.launchpad.net/elementary-os/stable/ubuntu artful InRelease
Hit:6 http://ppa.launchpad.net/go-for-it-team/go-for-it-daily/ubuntu artful InRelease
Hit:7 http://ppa.launchpad.net/nathan-renniewaldock/flux/ubuntu artful InRelease
Hit:8 http://ppa.launchpad.net/noobslab/icons/ubuntu artful InRelease    
Hit:9 http://ppa.launchpad.net/noobslab/macbuntu/ubuntu artful InRelease 
Hit:10 http://ppa.launchpad.net/noobslab/themes/ubuntu artful InRelease  
Hit:11 http://ppa.launchpad.net/papirus/papirus/ubuntu artful InRelease   
Err:12 http://ppa.launchpad.net/elementary-os/stable/ubuntu artful Release
  404  Not Found
Err:13 http://in.archive.ubuntu.com/ubuntu artful InRelease
  502  Connection timed out [IP: 2001:67c:1360:8001::21 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/elementary-os/stable/ubuntu artful Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.


$ sudo apt-get install com.github.babluboy.bookworm
Reading package lists... Done
Building dependency tree       
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 com.github.babluboy.bookworm : Depends: libgranite4 (>= 0.4.1) but it is not installable
E: Unable to correct problems, you have held broken packages.
``
i compiled libgranite from their github page after some user suggested in one of the above comments. That didn't help either.

**Comment by babluboy** [comment]
@amoghatr Thanks for the update. Based on the update it looks like elementary os is not available for Artful, I confirmed the same on the link below:
http://ppa.launchpad.net/elementary-os/stable/ubuntu/dists/

As a next step, I would have suggested building granite from github, but since you have used the Flatpak route - its fine. I have not tested all features of Bookworm using Flatpak so if you find any issue please do log an issue here on GitHub.
