### ISSUE TITLE
Question: how to go from search result page => a selection => then BACK to the search result page?

### ISSUE THREAD

**Issue by arooni** [babluboy/bookworm#173]
Obligatory I love your software note.  :+1: 

OK, now let's take this use case.  
0.  I want to search for some text in a particular book that I have opened.
1.  I enter the text I want to search 
2.  I find 4-5 matches!  Yay!  So I click the first text match result and go to that part of the book.  I decide that it's not what I wanted.
3.  I'd like to now simply go back to my search results, but I cannot!  I apparently must do the search all over again wasting time.  

IMHO It would be nice to be able to go back to the search result page somehow without performing the search again.

Hopefully this makes sense.

**Comment by arooni** [comment]
Nevermind; I just need to hit the 'info' button to get back there.

**Comment by babluboy** [comment]
@arooni That's correct, the results are preserved in the info tab for search. But makes me think if we should have a shortcut to go from reading mode to search results...that will make it more convenient...what say?
