### ISSUE TITLE
Scroll Bar width on WebKit not expanding on mouse over

### ISSUE THREAD

**Issue by torikulhabib** [babluboy/bookworm#175]
Not changed every mouse on scroll bar. i hope scroll bar like app other.

**Comment by babluboy** [comment]
@torikulhabib Sorry I don’t understand the issue you have raised. Is there an issue with the scroll bars in Bookworm? Will be great to see a screen shot of the issue?

Also are you using Bookworm on Elementary OS or some other distro?

**Comment by torikulhabib** [comment]
![scrollbarr](https://user-images.githubusercontent.com/26135527/35949328-810a6a3e-0ca3-11e8-9757-f908984402b2.png)

on elementary OS.
i hope scroll bar like scroll bar io.elemetaray.terminal 
can change size scroll bar every mouse on scroll bar

**Comment by babluboy** [comment]
Thanks for the screen shot - I can observe the behavior on the reading view where the scroll bar is not getting more wider on mouseover. I will check if this is an issue for webkit which is used in the reading view. The scroll bar on the library view is working correctly.

**Comment by babluboy** [comment]
@torikulhabib Pushed some changes to style the webkit webview scrollbar to make it wider on hover. Hopefully this resolves the issue. The CSS for styling is based on the suggested one in this [issue](https://bugs.launchpad.net/elementaryos/+bug/1591551) on Launchpad

This can be tested by building from source or by updating from the daily PPA

![scrollbar light](https://user-images.githubusercontent.com/14061478/36052702-a2949d20-0de6-11e8-91b1-7be21f0d2c52.png)
![dark scroll bar](https://user-images.githubusercontent.com/14061478/36052705-a705b4a2-0de6-11e8-90c2-b65b86ffdb56.png)
