### ISSUE TITLE
Pages are always entire chapter

### ISSUE THREAD

**Issue by JonasT** [babluboy/bookworm#176]
Each page seems to be just a continuous view of the entire chapter. I can't find any obvious way to get a paginated view where I can switch back and forth between pages. Is there one that I missed? page up/down seems to jump an arbitrary amount, cursor left/right jumps to entire next chapter...

**Comment by JonasT** [comment]
Sorry, I promise I looked over the issues but somehow missed "Pages Support" :smile:

**Comment by babluboy** [comment]
@JonasT No Probs. We will track the issue on #170. But just out of interest the up/down key should move the lines up and down like a browser i.e. by one line.
Also, bookworm should remember where the last read point in a page was and should open with that same view port. Does that help a bit? But I understand the need for pagination to avoid the hassle of scrolling through long chapters

**Comment by JonasT** [comment]
On February 9, 2018 6:17:40 PM GMT+01:00, Siddhartha Das <notifications@github.com> wrote:
>@JonasT No Probs. We will track the issue on #170. But just out of
>interest the up/down key should move the lines up and down like a
>browser i.e. by one line.

Yes it should in continuous mode, even though that's horrible / useless for faster human readers. I'm not saying change it, since it's kind of a design issue with continuous mode in general and some people like that mode. But the problem is that if you read fast, you either need to scroll so fast that it blurs too much for reading (and you inevitably lose track of the exact line and need to visually scan for it after the scroll) or so slow you can only read at like half your regular speed. Pagination avoids all of this because 1.) it's instant so you don't need to wait for it (unless it is animated, please don't do that) and 2.) you have the fixed point of visual reference of the top left corner to continue reading, hence no need to scan for the line you stopped at.

Page up/down would be better if it jumped pretty much exactly over what is visible on screen instead of the seemingly arbitrary amount they do now. However, since continuous mode still has issues like half cut-off lines at the bottom which require manual checking after a page jump whether you jumped unintentionally over them or not, this only makes continuous mode a bit more tolerable but it's no replacement for proper flexible pagination.

There is also the issue with embedded cover and images: many EPUBs are built with large images meant to scale to viewport/visual page size. Currently, bookworm cuts those off vertically at some arbitrary scale, since the notion of a surrounding page doesn't seem to exist in the layouting.

>Also, bookworm should remember where the last read point in a page was
>and should open with that same view port. Does that help a bit?

Not really, the issue is, as explained above, the way scrolling works in non-paginated mode, not so much finding your old spot again after a longer reading break where you browsed away from the document. Of course people who like continuous mode for books (I don't) will appreciate these additions.

**Comment by babluboy** [comment]
@JonasT Many thanks for the detailed write up - definitely gives me the motivation to add the pagination capability :+1:
