### ISSUE TITLE
snap fails to launch

### ISSUE THREAD

**Issue by popey** [babluboy/bookworm#178]
Bookworm looks awesome, so I installed it on my Ubuntu 18.04 system. Unfortunately it fails to launch.

```
$ snap run bookworm
ERROR: ld.so: object 'libgtk3-nocsd.so.0' from LD_PRELOAD cannot be preloaded (failed to map segment from shared object): ignored.
[INFO 14:10:27.073336] Application.vala:154: Bookworm version: (null)
[INFO 14:10:27.073374] Application.vala:156: Kernel version: 4.13.0-32-generic
[WARNING 14:10:27.073529] [Gtk] Locale not supported by C library.	Using the fallback 'C' locale.
Failed to register: GDBus.Error:org.freedesktop.DBus.Error.AccessDenied: Connection ":1.3011" is not allowed to own the service "com.github.babluboy.bookworm" due to AppArmor policy

```

**Comment by babluboy** [comment]
@popey Thanks for your interest in Bookworm - yes I have discovered issues in the bookworm snap, probably I should remove it from the stable channel. I have raised questions on these issues here but the one you report looks a bit different.

Meanwhile, you can install bookworm in two other ways on Ubuntu:
1- Install from the stable PPA
2- Install from Flatpak

Instructions for both of the above are here:
 [https://babluboy.github.io/bookworm/#install](https://babluboy.github.io/bookworm/#install)

Let me know if you manage to install using any of the above and if it works well on Ubuntu 18.04. I haven't tested the same myself.

**Comment by Ads20000** [comment]
Thanks for the recommendation, will use the Flatpak since that is the closest thing to a snap!

Not sure this is a 'distro issue', more an issue with the snap (and they run on many distros, though I guess it's primarily Ubuntu promoting them), the error seems to suggest that it's missing a plug of some sort? Not sure what.

**Comment by babluboy** [comment]
Ok...hopefully the flatpak install works. I will close this issue but feel free to update this if you run into further issues.

**Comment by Ads20000** [comment]
Could you take Bookworm out of the stable channel on the snap store because it doesn't work (as you suggested earlier)? :)

**Comment by babluboy** [comment]
@Ads20000 yes, good suggestion. Didn’t realise that I had put it on stable...will take it out.

**Comment by babluboy** [comment]
@Ads20000 Done. bookworm removed from stable channel on snapstore
