### ISSUE TITLE
Book Contents Page

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#18]
Having a side bar to show table of contents instead of a contents page so that the user can flip back easily to the page being read if he decides not to jump to a different page. And if the user does decide to jump to another page then the content side bar should disappear

**Comment by babluboy** [comment]
@choyan I have added a Resume button on the contents page to take the user back to where he was in case the user deceides not to jump to any other chapter on the content page

This can be a work around until I can implement a sidebar for the contents

**Comment by choyan** [comment]
@babluboy can't see the resume button in the latest build.

**Comment by babluboy** [comment]
@choyan The Resume button will only appear (where the Library button appears normally) when you are viewing the **contents page**. Clicking on the button will bring you back to the page of the book you were on. Clicking on the Content list will take you to that specific content. Here is how it comes up for me, let me know if you can see it when you go to the contents page of a book.
![resume button](https://cloud.githubusercontent.com/assets/14061478/23501022/298969c2-ff2a-11e6-8448-492f01ed87d6.jpeg)

**Comment by choyan** [comment]
Great! I was actually looking at everywhere else for the button. Working nice!

**Comment by babluboy** [comment]
Closing this as the "Resume" button achieves the functionality of going back to the page the user was on before coming to the Table Of Contents
