### ISSUE TITLE
Bookworm follows online links

### ISSUE THREAD

**Issue by kousu** [babluboy/bookworm#180]
Some books contain external (`http://`, `https://`, `ftp://`, `ftps://`, etc) links, for example [this one](https://leanpub.com/queerprivacy). I discovered that Bookworm _follows_ and loads these *inside itself* rather than spawning my system browser. And it does this without any display of what the link target is going to be.

This is a security risk and possibly a privacy violation. I don't have any control (like, [uBlock](https://github.com/gorhill/uBlock), Ghostery, ABP, Firefox Tracking Protection, Chrome safe browsing, noscript, ...) if I'm using a browser embedded in Bookworm. I don't know where I'm going, what cookies I'm taking in, what tracker scripts I'm loading. Does this mean bookworm could be **phoning home to tracking bugs** embedded in epubs or pdfs?

Relative, book-internal, links should be handled as they are. But external links should run `xdg-open`. 

In fact, Bookworm should *not* be making any network requests at all -- it should be [`pledge()`](http://man.openbsd.org/pledge)ing (BSD) or [`unshare()`](https://unix.stackexchange.com/a/83348)ing (Linux) the the network.

**Comment by kousu** [comment]
You need `CAP_SYS_ADMIN` and a recent kernel to use `unshare --net`, so maybe that's not appropriate for bookworm. It's weird; why would you need perms to *drop* privileges? Linux is whack.

**Comment by babluboy** [comment]
@kousu Many thanks for raising this issue. I completely agree with your point. For external links, Bookworm should use the user’s browser which are better equipped to deal with such links from a security perspective.

It should not be too difficult to catch external links on click and divert them to a browser

**Comment by Walker555** [comment]
I agree too. Nice-to-have features
1. show link URL in tooltip (mouse over)
2. add "copy URL" to right mouse click menu

**Comment by babluboy** [comment]
@kousu Added a fix to prevent external links loading on Bookworm. Only file:// links will load, otherwise the default browser will be used to load the link using xdg-open

**Comment by FedericoCeratto** [comment]
@babluboy is this addressing execution of javascript in the ebooks as well?

**Comment by babluboy** [comment]
No, javascript is required by bookworm itself to manipulate the look and feel like font change, margin adjustment, line width adjustment etc. I have not done anything to supress javascript present in the book content itself.

**Comment by FedericoCeratto** [comment]
This is a serious security problem. Can you please flag it in the README?
Can we open a dedicated issue?

**Comment by babluboy** [comment]
Can you elaborate on how javascript poses the security issues - we can then evaluate what is the additional exposure that the user will have if the epub is opened on a browser vs being opened on bookworm...
That will give me the quantification of the issue and possible testing and resolution if its indeed a exposure

**Comment by FedericoCeratto** [comment]
There are different issues independent from each other:
1. javascript allows network connections by design (!) leading to https://en.wikipedia.org/wiki/Phoning_home
1. javascript engines have a plethora of vulnerabilities and a poor track record. Here a random list: https://github.com/tunz/js-vuln-db
1. by executing potentially untrusted code the engine also gives access to hardware vulnerabilities on the host, for example https://en.wikipedia.org/wiki/Meltdown_(security_vulnerability)#History
1. browsers have very large attack surfaces in general

Bookworm does not provide clear warnings that ebooks will be opened in a browser.
