### ISSUE TITLE
cannot install on ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by snydez** [babluboy/bookworm#181]
Hi,
i try to install using ppa 
     *sudo add-apt-repository ppa:bookworm-team/bookworm*
error with 
     *The following packages have unmet dependencies:
     com.github.babluboy.bookworm : Depends: libgranite4 (>= 0.4.1) but it is not installable
     E: Unable to correct problems, you have held broken packages.*

when i follow steps in https://github.com/babluboy/bookworm#how-to-build-bookworm
already stuck on the first step
     *sudo apt-get build-dep granite-demo* 
with error
     *E: You must put some 'source' URIs in your sources.list*

is there any solution for such issue? 
thanks

**Comment by babluboy** [comment]
@snydez thanks for checking out bookworm. Looks like you are missing granite. You can run the following commands to add the elementary PPA and then try the Bookworm installation from PPA:
sudo add-apt-repository ppa:elementary-os/stable
sudo apt-get update
sudo apt-get install com.github.babluboy.bookworm

You can check the installation instruction on Bookworm’s website and if the PPA method still fails, you can try the Flatpak method:

https://babluboy.github.io/bookworm/#install

**Comment by troe** [comment]
Established as follows.
First added PPA repository:
sudo add-apt-repository ppa:bookworm-team/bookworm
sudo apt-get update

Later:
sudo add-apt-repository ppa:elementary-os/stable
sudo apt-get update
sudo apt-get install com.github.babluboy.bookworm

and everything turned out.
