### ISSUE TITLE
Failed on Build the Project using Make

### ISSUE THREAD

**Issue by swhp** [babluboy/bookworm#184]
Hi,

I tried to build the project using `make`, but got error below.
```
-- Checking for modules 'gtk+-3.0;gee-0.8;granite;webkit2gtk-4.0>=2.16.0;sqlite3>=3.5.9;poppler-glib;libxml-2.0'
--   No package 'gee-0.8' found
--   No package 'granite' found
--   
CMake Error at /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:363 (message):
  A required package was not found
Call Stack (most recent call first):
  /usr/share/cmake-3.5/Modules/FindPkgConfig.cmake:528 (_pkg_check_modules_internal)
  CMakeLists.txt:62 (pkg_check_modules)


-- Configuring incomplete, errors occurred!
```

Want to confirm is `gee` and `granite` package was necessary to build the code?
Thanks,

**Comment by babluboy** [comment]
@swhp yes, both packages are required. Gee is required for data structures like arrays to hold table of contents and library item objects. Granite is used for several things like remembering settings and widgets like toasts and message boxes...

Let me know what distro and version you are using and perhaps I can help...

**Comment by swhp** [comment]
I'm using Slackware 14.2, I think I need to build those package first.
Thank you for your quick response

**Comment by babluboy** [comment]
@swhp ok thanks. will close this issue. but do update back if you run into problems. and if you manage to get the same done, the details of how to get it done will be good to note here for other Slackware users.
