### ISSUE TITLE
Feature Suggestion: "Paged" mode (in contrast to "scrolling" mode)

### ISSUE THREAD

**Issue by nevilleomangi** [babluboy/bookworm#193]
Paged mode would be nice for reading view (for epub and mobi files). This would allow a user to use the arrow keys, for instance, to move from page to page rather than from chapter to chapter. Ideally, this would be responsive pages fitting the screen based on the font settings.

**Comment by babluboy** [comment]
Thanks for your interest in Bookworm. This feature is one of my top priorities and has been requested a couple of times (Issue #170). Hope you are fine with me in closing this one and tracking it on the mentioned issue#

**Comment by nevilleomangi** [comment]
Sure. Thanks. 
I had only browsed through the open issues. My bad.
