### ISSUE TITLE
Pressing f11 again does not return to normal mode

### ISSUE THREAD

**Issue by surajmandalcell** [babluboy/bookworm#194]
Pressing f11 does give me full screen view but pressing it again does not return back to normal view, and it is a bit inconvenient to press 'esc' on the other side to return back to normal.

Expected resulted : Pressing f11 should open full screen mode and pressing f11 again should return me back to normal viewing mode.

Actual result : Pressing f11 does give me full screen mode but pressing f11 again gives me no result (nothing happens).

**Comment by babluboy** [comment]
@surajmandalcell Agree to your views. Esc is one way someone might try to escape from a full screen, but quite possible that F11 is pressed again as a way to toggle the full screen back to normal. However, before I add that shortcut is there an application which uses F11 to toggle fullscreen ? That way we can ensure uniformity....

**Comment by surajmandalcell** [comment]
@babluboy Nope, i don't see any other app using this shortcut as of now so you're free to add this shortcut. I've always been using f11 to full-screen and full-screen-out (firefox,chrome,pdf readers,any presentation applications) and since using bookworm this has been bugging me. Thanks in advance :+1:

**Comment by babluboy** [comment]
@surajmandalcell Thanks. I asked if any other app used F11 to come out of full screen just to make sure that this pattern is followed commonly...like you have mentioned browsers, and other readers use the F11 to toggle full screen, so it makes sense to have the same for Bookworm.

Will use this issue to update back when I have added this code to enable F11 to come out of full screen
