### ISSUE TITLE
Impossible to Uninstall on Ubuntu 18.04

### ISSUE THREAD

**Issue by montaltoalessandro** [babluboy/bookworm#207]
Dear,

I installed bookworm via ubuntu software. I would like to uninstall it completely, but it seems to be impossible. when I typed

sudo apt-get purge bookworm

I got the message that it was impossible to find the bookworm package while I see the icon in the dash and when I search for bookworm I get a long list of file (view attachment please).

So, how can I uninstall bookworm?

Kind regards,

Alessandro
![schermata del 2018-07-13 11-30-55](https://user-images.githubusercontent.com/7261678/42684766-5a77a02c-8691-11e8-8113-ab253eee6b14.png)

**Comment by babluboy** [comment]
@montaltoalessandro Thanks for raising this - I had not checked out the uninstall function to see if I need to set up any config during installation to have a clean install. Will use this issue to track.

The following is where bookworm installs its components, so you can manually remove the same:
1. Icons: /icons/hicolor/16x16/com.github.babluboy.bookworm.svg and similarly in the 24x24, 32x32, 48x48, 64x64 and 28x128 folders in hicolor
2. Executable to be removed: /usr/bin/com.github.babluboy.bookworm
3. Contract file to be removed: share/contractor/om.github.babluboy.bookworm.contract
4. Config data to be removed by removing the "bookworm" folder in ~/.config
5. All other components can be deleted by removing the "bookworm" directory under /usr/share
6. Locale files: Remove the com.github.babluboy.bookworm.mo file in /usr/share/locale under various sub folders like aa/LC_MESSAGES, ab/LC_MESSAGES. i.e. /usr/share/locale/aa/LC_MESSAGES/com.github.babluboy.bookworm.mo

 Hopefully in the next release, I will move most of the binaries and schemas into the executable using gresource which will make the uninstall cleaner. Let me know how you get along with the manual removal.

**Comment by babluboy** [comment]
@montaltoalessandro Forgot to ask you the reason why you did not want to use bookworm, anything I could do to improve your experience or a missing feature ?

**Comment by montaltoalessandro** [comment]
Great, thanks a lot, I managed to delete the main folders and com.github.* files. I deleted the rest by using

sudo find -type f -name '*babluboy*' -delete

from the root directory.

About bookworm: I find the project very interesting, but I probably missed something because I installed it via ubuntu software and it never loaded the content of my epub books while my ebook reader was perfectly able to read the same files. I then decided to clean my pc a bit and uninstall all the programs that I wasn't using.

kind regards,

Alessandro

**Comment by babluboy** [comment]
@montaltoalessandro Thanks for the update. I will spin up a Ubuntu VM and install from store to see if I can replicate the issue. 

You can install from the PPA or build from source if you want to install again. Instructions here:
https://babluboy.github.io/bookworm/

**Comment by montaltoalessandro** [comment]
@babluboy thanks for the info :) I also tried to reinstall and uninstall bookworm again from the repository and it actually worked, showing two icons of bookworm in the dash. the second one was removed pretty fine. I don't get what went wrong with the first version.

**Comment by alxfed** [comment]
Closed?

No, it hasn't been 'closed' f...ing idiot!
