### ISSUE TITLE
Cannot Read Specific EPUB Book

### ISSUE THREAD

**Issue by infosisio** [babluboy/bookworm#212]
The attached book is not readable, if you open it with latest version, there is text all over the place overlapping other text. I have put it in a zip to attach it on Github.
[Great Expectations.epub.zip](https://github.com/babluboy/bookworm/files/2320803/Great.Expectations.epub.zip)

**Comment by babluboy** [comment]
@infosisio Thanks for taking time to raise this issue. This has been reported by other users as well - I have seen this on the first chapter of epubs downloaded from Gutenberg.
Closing this issue as duplicate and will track the same via Issue #210
