### ISSUE TITLE
Linux Mint

### ISSUE THREAD

**Issue by usolmz** [babluboy/bookworm#213]
Linux Mint Yazılım Yöneticisinde yerini ne zaman alır?

**Comment by babluboy** [comment]
Translated to: When does Linux take its place in Mint Software Manager?

I think you are asking if Bookworm is available on Mint Software Manager. This issue (#290) is open for the same, however the Mint user has not resolved the details for getting Bookworm to work on Mint. You can try building from source or use Flatpak.

Closing this issue and we can track it on the other referenced issue for Mint.
