### ISSUE TITLE
Book isn't deleted

### ISSUE THREAD

**Issue by ItsPossibleAlready** [babluboy/bookworm#216]
i deleted my book than i restarted program (BookWorm) and that book appear again

**Comment by ItsPossibleAlready** [comment]
The Program from flatpak with 1.0.0 version

**Comment by babluboy** [comment]
@ItsPossibleAlready When you delete a book in the Bookworm's library, the actual ebook file is not deleted and only the cached contents of the book and its details from the bookworm library are removed. If the ebook file is in a watched folder ("Add folders to scan for books") then it will be automatically re-added to the library on re-start.

Can you make sure that the ebook file (i.e. .epub, .pdf, etc) is not present in the watched folder or alternatively no folders are set up for watching in the Bookworm preferences as shown below:

![screenshot from 2018-09-26 18 29 36](https://user-images.githubusercontent.com/14061478/46097577-3a3db300-c1ba-11e8-9e98-e53f2bee9b37.png)

**Comment by ItsPossibleAlready** [comment]
OK, Thank you.
