### ISSUE TITLE
After Deleting the books, the Library doesn't get refreshed.

### ISSUE THREAD

**Issue by choyan** [babluboy/bookworm#22]
After Deleting the books, the Library view should be refreshed. Currently, it's causing some problems. After removing 2 books from the Library, its showing blank spaces in the deleted books area. I've deleted 2 books from the Library from the bottom area.

![screenshot from 2017-02-27 12 44 37](https://cloud.githubusercontent.com/assets/1283240/23351339/b6353c62-fcea-11e6-845e-24c2e91220fd.jpeg)

**Comment by babluboy** [comment]
@choyan Yes, I have noticed this myself. Should be an easy fix

**Comment by babluboy** [comment]
Fixed the issue of deleting books leaving a white space in the Library View
