### ISSUE TITLE
Supported formats

### ISSUE THREAD

**Issue by Dirli** [babluboy/bookworm#226]
If it's not difficult for you, change the installation of the supported formats to the optional (for example: meson_options.txt from elementary-code). it would be great

**Comment by babluboy** [comment]
@dirli Just to understand the context of how this change will benefit users - does this mean while installing I have the choice whether to install components just required for Bookworm to open ePubs and not any other format like CBZ for example?

If this is achievable by meson options then how will Appcenter support it? There will be very few users who will install Bookworm from source

**Comment by Dirli** [comment]
To install by yourself and for Gentoo users)))

**Comment by babluboy** [comment]
Sure...I have always thought Bookworm will be cross distro compatible. If you have been able to install on Gentoo then can you please provide a quick set of installation commands - I will add it to the Bookworm website. 

But just on this issue, I am thinking whether it will be helpful to install only specific formats as one of the goals of Bookworm is to let the user read books without worrying about the format and support as many formats as possible...
