### ISSUE TITLE
Scalability - Library Pagination

### ISSUE THREAD

**Issue by infosisio** [babluboy/bookworm#232]
I'd like to ask how scalable the program is, in the sense of what number of books the library can host?

Thanks!

**Comment by babluboy** [comment]
I had tested with a library of 100 books and it loaded properly. However it will slow down at one point with larger libraries as I’m loading all the books at once. I have an issue open to create pagination of the library and load in batches - first view can be the 20 books used recently, then if the user moves to the second page load the next 20 and SI on...that will definitely scale it to load a library of any size


Issues #145 #156

**Comment by infosisio** [comment]
@babluboy This needs to be high priority. 100 books is a really small library. If possible, there should be no limit.

**Comment by babluboy** [comment]
@infosisio Yes, agree that there should be no limit to the books in the library and it should not affect performance of bookworm. Will see when I can get some time from my day job to work on the library pagination.

**Comment by infosisio** [comment]
@babluboy Any updates so far? :)

**Comment by babluboy** [comment]
Sorry - I didnt have much time for bookworm this year so far, will have to find time soon to get back on the growing issue/feature list...

**Comment by babluboy** [comment]
Initial changes for library pagination done. Following are completed:
1- 21 books are loaded at a time with the ability to go forward and backward in the library collection
2- Books are sorted based on the last opened time (books added and read come in the first page) 

To be done next:
1- implement the search to work across the library (not just the books in the current page of the library)
2- code cleanup of certain variables which accumulate data. pagination needs to remove data from these accumulators
3- provide a preference for the number of books to be loaded at a time - default value of 21 looks a nice fit in the library without the vertical scroll bar

**Comment by babluboy** [comment]
Hopefully this completes the library pagination:
1- Paginated Library view: Both grid covers and lists view (Bookworm will not attempt to load the whole library and hence this will loading of large libraries i.e. >1000000 possible without time lag)
2- Ability to search for books by title, tags, author, etc respective of whether the book is present in the current page
3- Ability to flip through the library by the buttons on the foot as well as with the forward and backward arrow keys
4- Ability to set the number of books per library page as a Preference item (the default will be 21)

Will do some more testing on this before releasing the same on appcenter. Any testing and feedback welcome - will have to build from source to get the latest code as per the instructions [here](https://github.com/babluboy/bookworm#building-testing-and-installation)

![Library Pagination](https://user-images.githubusercontent.com/14061478/59331988-e3114b80-8d12-11e9-81db-c1b4e3bee510.png)
