### ISSUE TITLE
Cancelling open book dialog after opening it from home with empty db make it disappear

### ISSUE THREAD

**Issue by Porkepix** [babluboy/bookworm#235]
Steps to reproduce:
- Run bookworm with an empty DB
- Click Open button in the middle of the screen
- Once dialog is open, hit `escape` or `cancel`
- Home changed as if DB was not empty anymore, while nothing was added

**Comment by babluboy** [comment]
@porkepix Thanks for raising this issue. Definitely looks like a condition I’m not testing to check if any book was added before removing the welcome screen. Should be an easy fix.

**Comment by babluboy** [comment]
Added condition to remove the welcome screen only if books were selected. However, if the selected books were not added to bookworm (i.e. failed to parse) then the blank library will be shown. However this is a rare case scenario so ignoring for now.
