### ISSUE TITLE
Getting "Bus error" on FreeBSD

### ISSUE THREAD

**Issue by 0mp** [babluboy/bookworm#242]
I compiled Bookworm on FreeBSD but when I execute `com.github.babluboy.bookworm` I get:

> Bus error

**Comment by babluboy** [comment]
@0mp From a quick google search looks like this is a common issue on FreeBSD. However, I have not found a common solution to fix the issue. Let me check further.

**Comment by 0mp** [comment]
Let me know if I can provide any additional information ;)

**Comment by NitroNils** [comment]
FreeBSD 13 just around the corner (end of March?).
Maybe this problem magically goes away?

**Comment by 0mp** [comment]
There are some patches available here: https://reviews.freebsd.org/D25569

I've compiled them and run the test suite. Unfortunately, the test suite fails. I've not tested if the GUI actually work, AFAIR.

**Comment by 0mp** [comment]
The port has been committed: https://www.freshports.org/deskutils/bookworm/

Here's the commit introducing Bookworm to the FreeBSD Ports Collection: https://cgit.freebsd.org/ports/commit/?id=1fe029273d1ecf6dbf40da326cf8388ffda7a949. We had to patch a couple of files (e.g., in order to switch to Python 3).

CC @mgocobachi
