### ISSUE TITLE
FUNCTION:createAnnotationDialog when read specific epub files 

### ISSUE THREAD

**Issue by dmitriiweb** [babluboy/bookworm#243]
The application can't render some epub files. When I click on a book in the Library, I see only empty pages. When I click navigation button then appear pop-up dialog "Edit annotation for <link rel="stylesheet" href..."
[debug.txt](https://github.com/babluboy/bookworm/files/2896876/debug.txt)

**Comment by babluboy** [comment]
@dmitriiweb Many thanks for your interest in Bookworm and logging this issue.
Would you be able to attach the mobi file giving the issue or send it to my email: bablu.boy@gmail.com

I will try and reproduce the issue at my end to help me debug the issue.

**Comment by dmitriiweb** [comment]
@babluboy I've sent you an email

**Comment by dmitriiweb** [comment]
@babluboy Also you can use any epub file from this website: http://flibusta.is/

**Comment by babluboy** [comment]
Thanks - I have replicated the issue. There must be some content in the epubs from this site that is conflicting with the code. Will check and let you know as sook as I fix it

**Comment by dmitriiweb** [comment]
@babluboy 
Thanks.
I also checked such files in other readers, and they read these files without any issues.

**Comment by babluboy** [comment]
@dmitriiweb Turns out that this was caused by an empty title tag in the ebook contents i.e. <title />
I have made a fix to remove the empty title tag before rendering the contents, and it seems to have fixed the issue. Will be great if you can build from source and test it on some of the books on [http://flibusta.is/](http://flibusta.is/)

Hopefully this makes Bookwork a bit better and compatible in handling books with empty title tag contents.

**Comment by dmitriiweb** [comment]
Excellent! Thank you!

**Comment by babluboy** [comment]
@dmitriiweb No worries. Let me know when you have checked and confirm the fix works for opening the similar books from [http://flibusta.is/](http://flibusta.is/) which were having the issue earlier.

**Comment by dmitriiweb** [comment]
@babluboy Thank you, all working fine. Awesome!

**Comment by babluboy** [comment]
great !...thanks for checking.
Will try to put in some more changes/fixes and release this as part of 1.1.2 release
