### ISSUE TITLE
Inbuilt Dictionary?

### ISSUE THREAD

**Issue by Sparsa** [babluboy/bookworm#246]
Is it possible to get inbuilt dictionary, such that whenever we select a word it shows the meaning(like google-play books)

**Comment by babluboy** [comment]
@Sparsa Thanks for your interest in Bookworm.
Did you mean a local offline dictionary ? The current one should work if you have internet connection.
For an offline one, the script in the user's home directory needs to be modified as mentioned in #185 
Does this help?

**Comment by babluboy** [comment]
@Sparsa I forgot to mention that dict needs to be installed in the system for the offline dictionary to work. If you have got dict, then comment/un-comment the relevant lines as specified in #185
