### ISSUE TITLE
Bookworm unable to fetch books in Local network/remote storage

### ISSUE THREAD

**Issue by sam5558** [babluboy/bookworm#247]
First of all i wanted to thank for your project, very clean and beautiful book reader for linux.
Unfortunately, i'm unable to use this client for my daily usage because bookworm is unable to fetch content from my local network (i have a Synology).
To be more specific, bookworm should incorporate either OPDS support, NFS and/or SAMBA support for people like me who have a dedicated network storage for books/manga/comics/BD... to be able to enjoy this pretty clean client.
This issue is more an enhancement than an issue but anyway. 
Thanks for your time

**Comment by babluboy** [comment]
@sam5558 Thanks for your interest in Bookworm. On Elementary OS if I have a drive mounted (Samba Share, FTP, etc) I can see the drive and its content in the file open dialogue when I choose to add a book to the Bookworm library.

Is it not the case for you? What distro are you on? Can you try mounting the share drive on which your ebooks are located such that you see them from a file explorer. Then adding them to Bookworm should work. 

If it does not work then after mounting the share, start Bookworm in debug from a terminal and put the contents on this issue:

1. com.github.babluboy.bookworm —debug > ~/bookworm.debug.txt

2. In Bookworm try adding a book and open the shared folder in the dialog

3. Then attach the debug log from your home directory.

**Comment by babluboy** [comment]
Closing this issue as it seems it would be a permission issue due to which bookworm is not able to add books on a remote mounted folder. Please re-open the issue if it persists and add the debug file by running the command suggested above.
