### ISSUE TITLE
No notification when Book in Library is not available

### ISSUE THREAD

**Issue by choyan** [babluboy/bookworm#25]
After the previous update, the ebook reader is not working. It can't show any content.
Error code:

>[_LOG_LEVEL_DEBUG 14:51:40.653114] utils.vala:346: Started file operation[READ_FILE], for path=false, filename=
>[_LOG_LEVEL_WARN 14:51:40.665250] utils.vala:488: Failure in File Operation [operation=READ_FILE,path=false, filename=]: Failed to open file 'false': No such file or directory
>[_LOG_LEVEL_DEBUG 14:51:40.665305] utils.vala:491: Completed file operation[READ_FILE]...
>[_LOG_LEVEL_DEBUG 14:51:40.665361] ePubReader.vala:173: Completed extracting location of content files in ebook. Number of content files = 0
>[_LOG_LEVEL_DEBUG 14:51:40.665393] ePubReader.vala:178: Starting to renderPage for direction[] on book located at /media/choyan/Sherlock/Books/f-BeastsFind/Fantastic Beasts and Where to Find T (21)/Fantastic Beasts and Where to F - J. K. Rowling.epub
>[_LOG_LEVEL_DEBUG 14:51:40.665435] ePubReader.vala:199: Book has a CURRENT_LOCATION set at :13
>[_LOG_LEVEL_WARN 14:51:40.665461] ePubReader.vala:221: No contents determined for the book at location [13], no rendering possible.

**Comment by babluboy** [comment]
Confirmed that the issue occurred when a Book added previously into Bookworm was on a drive which was not mounted when the attempt to read it was made. However, there was no notification provided to the user that the book is not available at the location it was when it was added to the library. Add a notification bar to issue such messages to the user

**Comment by babluboy** [comment]
Added a Message Bar to show that the Bookworm cannot load the selected book if the book cannot be found at the specified location from where it was added or if the contents of the book cannot be parsed correctly
![bookworm - warning message](https://cloud.githubusercontent.com/assets/14061478/23817376/8a2ca5a2-05ea-11e7-9ab2-a305376fb0cf.jpeg)
