### ISSUE TITLE
libgranite5 depency for ppa:bookworm-team/bookworm

### ISSUE THREAD

**Issue by kelebek333** [babluboy/bookworm#253]
Hi,

Could you add missing depency (libgranite5) to ppa:bookworm-team/bookworm.

Best regards

**Comment by babluboy** [comment]
Hi, Thanks for raising this issue. Here is a workaround to get libgranite by including the elementary ppa temporarily as mentioned here : [https://babluboy.github.io/bookworm/#install](https://babluboy.github.io/bookworm/#install)

I have got this for libgranite in [debian/control](https://github.com/babluboy/bookworm/blob/080e89a351a7084e71271f282185db112182d49b/debian/control#L11) : libgranite-dev (>= 0.3.0), maybe I should bump the version to 0.5.0 ?

**Comment by babluboy** [comment]
moved granite version to 0.5 in debian control
