### ISSUE TITLE
Title of the headerbar changes after exiting book

### ISSUE THREAD

**Issue by tim4tech** [babluboy/bookworm#257]
Not sure if this is expected behavior but the headerbar title will initially be "Bookworm" but once a book is loaded and then you return back to the library view, the headerbar title will be changed to "eBook Reader". Not sure if this was intended or not.

Version: 1.1.2

**Comment by dass-inflexi** [comment]
@tim4tech thanks for your interest in bookworm and good catch ! The standard behaviour should be the title of the book while the user is reading the same and "eBook Reader" at all other time.

Will fix the initial load title which wrongly puts the title as Bookworm.

**Comment by babluboy** [comment]
Fixed issue to set the initial header bar title as "eBook Reader"
