### ISSUE TITLE
No images being displayed - Gnucash Help and Concepts Guides

### ISSUE THREAD

**Issue by bdika** [babluboy/bookworm#262]
I am unable to see the illustrations in the Gnucash epub documentation.

Initially I was getting an error when trying to open them but followed the advice about mimetype problems on this site and got them to load into Bookworm.

However, all illustrations just show a placeholder.

I downloaded the epub files from the Gnucash documentation site.

Any help would be much appreciated.

I am using bookworm on Elementary OS Juno.

Thanks.

Bill Dika

**Comment by babluboy** [comment]
Many thanks for raising this issue and your interest in bookworm. Let me download an epub from Gnucash docs and test the same.

**Comment by babluboy** [comment]
Did the following and there was no issue in the images being displayed.
1- Dowloaded the epub from: https://www.gnucash.org/docs/v3/C/gnucash-help.epub
2- There was no mimetype file, so added the same to the extracted contents and zipped up the same back again and renamed the zip to epub and it opened fine in bookworm
3- The images are being displayed correctly.

I have attached my modified epub, may be you give that a try and also attach the epub you are having problems with to this issue and I will investigate

![gnucash](https://user-images.githubusercontent.com/14061478/59155742-f7a0da00-8aad-11e9-8b83-1f73d9dea8b1.png)


[gnucash-help-modified.epub.zip](https://github.com/babluboy/bookworm/files/3269289/gnucash-help-modified.epub.zip)

**Comment by bdika** [comment]
Hi babluboy:
Thanks for the gnucash-help-modified.epub file. It is working now.
I tried to follow your suggestion with the gnucash v3 concepts guide epub file without any luck.
Attached is the file
[gnucash-guide-my.epub.zip](https://github.com/babluboy/bookworm/files/3270617/gnucash-guide-my.epub.zip)
 that is giving me problems.
Thanks for helping with this

**Comment by babluboy** [comment]
I removed the .zip extension from the file you attached and opened in Bookworm and had a quick look and it looks like the images are being displayed fine. Is there a specific page you want me to check. 


You can also run bookworm in debug mode by opening terminal and executing the command:
`com.github.babluboy.bookworm --debug > ~/bookworm.txt`
Then open the book and navigate to the page where images are not being displayed. Close bookworm and attach the bookworm.txt file here to see if I can spot anything from the debug text.

![Screenshot from 2019-06-11 17 37 56](https://user-images.githubusercontent.com/14061478/59270904-3d0d0500-8c70-11e9-93c6-64507cddc222.png)

**Comment by bdika** [comment]
Hi babluboy:

Attached is the bookworm.txt file. I think I opened it on page 13 of the epub file. There were placeholders where the images should have been. Attached is a screen shot.


![bookworm](https://user-images.githubusercontent.com/10201261/59283922-5cd50680-8c39-11e9-90ef-5bfe00baa038.png)


Thanks.

Bill Dika
[bookworm.txt](https://github.com/babluboy/bookworm/files/3277181/bookworm.txt)

**Comment by babluboy** [comment]
Thanks for the debug output. When I opened pg13, the pictures appear fine (screen shot below).
Then I compared the debug output of how bookworm loaded the pictures.
This is your output:
`Completed execution of sync command [find "/home/dad/.config/bookworm/books/gnucash-guide-my.epub" -name "basics_SaveXML.png"] with output:/home/dad/.config/bookworm/books/gnucash-guide-my.epub/OEBPS/figures/basics_SaveXML.png/home/dad/.config/bookworm/books/gnucash-guide-my.epub/gnucash-guide/OEBPS/figures/basics_SaveXML.png`

And this is my output:
`Completed execution of sync command [find "/home/sid/.local/share/com.github.babluboy.bookworm/books/gnucash-guide-my.epub" -name "basics_SaveXML.png"] with output:/home/sid/.local/share/com.github.babluboy.bookworm/books/gnucash-guide-my.epub/OEBPS/figures/basics_SaveXML.png`

Looks like you had an older version of bookworm which stored contents in the ".config" folder under home directory and the latest version of bookworm stores contents under ".local/share/" folder under home directory. 

Can you remove the book from bookworm and re-add it to see if it resolves the issue.

![pg-13](https://user-images.githubusercontent.com/14061478/59326047-ddac0500-8d02-11e9-81a3-5c15066bf854.png)

**Comment by babluboy** [comment]
Closing this issue. Please re-open if you see the issue persisting.
