### ISSUE TITLE
Extremely long import times for large pdf libraries causes confusion

### ISSUE THREAD

**Issue by stuarttempleton** [babluboy/bookworm#265]
I wanted to pass along my experience importing a large library of PDFs. The import process runs after the app closes currently (I think the tool tip said as much). There's no visual cue to the user that an import is happening if you start the application while it is importing, so for very large libraries of PDFs, this can appear that the import isn't working.

pdftohtml is running in the background, so it's technically working, but I wouldn't have known (and almost uninstalled bookworm thinking it wouldn't work with my library) had I not checked the ps list. In my example, it's been churning through PDFs for 20 minutes.

As a user, if I start the app while a large import is happening, I would like to be told.

Hope this is helpful!

**Comment by babluboy** [comment]
@stuarttempleton Many thanks for your interest in bookworm and taking the time to raise this issue. Completely agree with your views. There should be a visual indication of the import process to let the user know that the import is working correctly. This has been suggested by other users as well and is being tracked via #259. I will close this issue and track this through #259.
