### ISSUE TITLE
Update Build / Dependency Instructions

### ISSUE THREAD

**Issue by aparmar** [babluboy/bookworm#286]
needed some additional things for build environment on Debian 10

**Dependencies:** Add appstream, gettext

**Build environment:** A build folder already gets created, and therefore "mkdir build" wouldn't work. Need to add -p, to make it "mkdir -p build && cd build". This will create the folder if it doesn't exist. Or just ignore that part of the instructions.  

Lastly it would be nice to have the dependencies listed in one line so it would allow copy/paste into a console. Here is what I used: 

`sudo apt-get install libgranite-dev webkit2gtk-4.0 libwebkit2gtk-4.0-37 libsqlite3-dev poppler-utils libpoppler-glib-dev html2text curl meson valac appstream gettext
`

With the info above, hopefully it's just a mattering of updating the readme :)

**Comment by babluboy** [comment]
@aparmar Thanks for the suggestions. I will make the changes to the build instructions on the ReadMe and also on the Bookworm website : https://babluboy.github.io/bookworm/#install

**Comment by babluboy** [comment]
I have now synced the build dependencies between the ReadMe and the [Website](https://babluboy.github.io/bookworm/#install). I have also added the mkdir -p option for the build instructions. There were some more dependencies like python2 which I have added to the list.

Hopefully this fixes the issue. Will be great if you can take a look and review for correctness.

**Comment by aparmar** [comment]
@babluboy thanks for making the updates so quickly!
