### ISSUE TITLE
No books are discovered due to whitespace in find command

### ISSUE THREAD

**Issue by AnonFuncsAreAwesome** [babluboy/bookworm#288]
Commit https://github.com/babluboy/bookworm/commit/b88d671d50d5fcec4bc6981c3e7354c6cd904887 changed the find command that's issued to discover books in a folder from
```! -readable -prune -o -type f \\( -iname \\*.mobi -o -iname \\*.pdf -o -iname \\*.epub -o -iname \\*.cbr -o -iname \\*.cbz \\) -print```
to
```! -readable -prune -o -type f \\ ( -iname \\*.mobi -o -iname \\*.pdf -o -iname \\*.epub -o -iname \\*.cbr -o -iname \\*.cbz \\) -print```.

File related: https://github.com/babluboy/bookworm/blob/df586ed2b8aa0659b88781f7ad4add9b1af71ce4/src/backgroundTasks.vala#L63

This renders to command unusable, exiting with
> ** (com.github.babluboy.bookworm:124924): WARNING **: 15:46:10.150: utils.vala:95: Execution of sync command [find "/data/eBooks" ! -readable -prune -o -type f \ ( -iname \*.mobi -o -iname \*.pdf -o -iname \*.epub -o -iname \*.cbr -o -iname \*.cbz \) -print]: exited with non zero error code[256]. Error message:find: paths must precede expression: ` ('

Removing the whitespace infront of the first '(' makes it work again.

**Comment by babluboy** [comment]
Many thanks for your interest in Bookworm. It’s strange how the discover function was working so far with the space on Elementary OS....I will check if it works fine without the space and merge your PR....

Did you test this on eOS or on another distro?

**Comment by babluboy** [comment]
Ah I see what you mean. The commit you have sighted was a PR I merged - that looks like has created the space in the find command
