### ISSUE TITLE
[Fix] Text formatting on readme.md (install instructions)

### ISSUE THREAD

**Issue by lihuelworks** [babluboy/bookworm#296]
The portion that details the install information is like this

> Run the command below to install the above on Ubuntu and Debian distros: sudo apt-get install unzip poppler-utils unar html2text python2 libgtk-3-dev libgee-0.8-dev libgranite-dev libsqlite3-dev libxml2-dev webkit2gtk-4.0 libwebkit2gtk-4.0-37 libpoppler-glib-dev meson valac gettext curl ninja appstream

...when it should be code formatted like this:

> Run the command below to install the above on Ubuntu and Debian distros:
> `sudo apt-get install unzip poppler-utils unar html2text python2 libgtk-3-dev libgee-0.8-dev libgranite-dev libsqlite3-dev libxml2-dev webkit2gtk-4.0 libwebkit2gtk-4.0-37 libpoppler-glib-dev meson valac gettext curl ninja appstream`
> 

A small dumb fix, but it should avoid people skipping some of the install instructions.

**Comment by babluboy** [comment]
@lihuelworks Very helpful suggestion, should be an easy fix
