### ISSUE TITLE
mobi support uses python2

### ISSUE THREAD

**Issue by bhepple** [babluboy/bookworm#307]
I'm trying to package bookworm for fedora but we are not allowed to include python2 code. The scripts in data/scripts/mobi_lib are python2 so I have to exclude them.

This does not appear to affect the functionality of reading .mobi files (although I have no DRM-encumbered .mobi files to test) so I want to ask you:

* are there any consequences to excluding the mobi_lib code that could cause user grief eg a crash?

* can this code be changed to python3?

**Comment by babluboy** [comment]
@bhepple Sounds strange that without Python2 how the mobi unpack is working. Note that once the mobi file is unpacked, bookworm does not need python to render the book in the library and for reading the same. Its just used for extracting the html content out of the .mobi file.

Per Issue #241 I can look to port the mobi unpack library to Python3 keeping python2 for backward compatibility, however the longer term goal is to remove the python dependency and rewrite the unpacking logic in vala

**Comment by bhepple** [comment]
Hmmm - you're quite right. I just tried it again and got an error message
''Problem in extracting contents of book...."

I don't know what I could have done wrong this morning when I first tried
it - maybe not enough coffee.

So it seems that at least there is no crash, we just can't read .mobi
format.

The choice then is either:

* to release in fedora without .mobi support (and a note to that effect in
the RPM description)

or

* to wait for the python3 code

I'm going to let you decide - it's your software, after all!

Please let me know what you decide


Thanks and stay healthy!!


Bob

**Comment by babluboy** [comment]
What timelines are you looking at for Fedora Packaging ?  I guess it will take me till this weekend to test and upgrade to Python3

**Comment by bhepple** [comment]
Hi Siddhartha

I'm new at this but I would imagine that it will take another 1-2
weeks to get the existing package (less the python2 elements) through
testing.

If I go to a new release I'd need to start with a formal review so
that could add another week or so.

fedora is slow, careful and conservative

Cheers


Bob

**Comment by babluboy** [comment]
@bhepple I have updated the mobi unpack library to the new version which works with Python2.7/Python3. If you can compile and test the latest code, the mobi files should now open with Bookworm.

Hopefully this resolves the issue and you can continue to package Bookworm for Fedora. Let me know in case of further issues and also once the package is available for Fedora, can you please update here on how Fedora users can install Bookworm so that I can add the instructions to the Bookworm website.

Thanks again for your help in making Bookworm available on Fedora.

**Comment by bhepple** [comment]
That's great news!

I'll get back onto the new code tomorrow (it's late here in Aus)

Cheers


Bob

**Comment by bhepple** [comment]
Hi Siddhartha,

The new python scripts work on my (very limited) collection of .mobi files.
Have you been able to test against DRM-protected .mobi files?

I will resume packaging soon - in the meantime, fedora-31 and -32 users can
install the COPR version (with python backported from master) with:

sudo dnf copr enable wef/bookworm
sudo dnf install bookworm

Cheers


Bob
