### ISSUE TITLE
Segmentation fault - ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded

### ISSUE THREAD

**Issue by hm400** [babluboy/bookworm#308]
Bookworm snap does not launch, running bookworm from cli with and without sudo produces these messages on Ubuntu 18.04, KDE Plasma5, Bookworm Snap installed with --edge --devmode options.

> ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
> /snap/bookworm/2/bin/desktop-launch: line 286: 12052 Segmentation fault      (core dumped) $RUNTIME/usr/lib/$ARCH/libgtk-3-0/gtk-query-immodules-3.0 > $GTK_IM_MODULE_FILE
> ERROR: ld.so: object 'libesets_pac.so' from /etc/ld.so.preload cannot be preloaded (cannot open shared object file): ignored.
> Segmentation fault

`

**Comment by babluboy** [comment]
@hm400 Apologies, I have not been able to work with snap packaging for Bookworm. Had faced a lot of issues and gave up on the same. If someone is willing to maintain the snap package, I will be happy.
