### ISSUE TITLE
Design Category View

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#32]
Design a capability for users to categorise their books in bookworm and then filter by category...

**Comment by babluboy** [comment]
I am thinking of tags that you can add to a book so the complete control will be with the user for categorisation...and then perhaps show a side pane view for various tags available and the user can then click on a tag to limit the library view to books matching that tag...something similar to Photos?

**Comment by choyan** [comment]
Great Idea! Just like the Photos app, the left sidebar will show the category view on the left side. And the category add button will be below the category list.

**Comment by babluboy** [comment]
This is similar to #45 and will be covered by the solution adopted for #45
