### ISSUE TITLE
The repository 'http://ppa.launchpad.net/bookworm-team/bookworm/ubuntu focal Release' does not have a Release file.

### ISSUE THREAD

**Issue by migueltorrescosta** [babluboy/bookworm#321]
When running
`sudo add-apt-repository ppa:bookworm-team/bookworm`
I get

```
 PPA for stable build of Bookworm
 More info: https://launchpad.net/~bookworm-team/+archive/ubuntu/bookworm
Press [ENTER] to continue or Ctrl-c to cancel adding it.

Hit:1 http://hu.archive.ubuntu.com/ubuntu focal InRelease
Hit:2 http://hu.archive.ubuntu.com/ubuntu focal-updates InRelease                                                                             
Hit:3 http://hu.archive.ubuntu.com/ubuntu focal-backports InRelease                                                                                                                                               
Ign:4 http://ppa.launchpad.net/bookworm-team/bookworm/ubuntu focal InRelease                                                                                                                                      
Hit:5 http://dl.google.com/linux/chrome/deb stable InRelease                                                                                                                               
Get:6 http://security.ubuntu.com/ubuntu focal-security InRelease [107 kB]                                       
Hit:7 http://ppa.launchpad.net/ubuntu-mozilla-daily/firefox-aurora/ubuntu focal InRelease                                  
Hit:8 http://packages.microsoft.com/repos/vscode stable InRelease              
Err:9 http://ppa.launchpad.net/bookworm-team/bookworm/ubuntu focal Release          
  404  Not Found [IP: 91.189.95.83 80]
Reading package lists... Done
E: The repository 'http://ppa.launchpad.net/bookworm-team/bookworm/ubuntu focal Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
N: See apt-secure(8) manpage for repository creation and user configuration details.
```

Is there a way of installing bookworm without enabling non-secure ppa repositories?

EDIT: I am installing this from Ubuntu 20.04 . If there is any other useful information I can provide do not hesitate to ask :)

**Comment by bhattisatish** [comment]
I am getting the same error on *Ubuntu 20.04*
The `add-apt-repository ppa:bookworm-team/bookworm` fails with the following error
    
    E: The repository 'http://ppa.launchpad.net/bookworm-team/bookworm/ubuntu focal Release' does not have a Release file.
    N: Updating from such a repository can't be done securely, and is therefore disabled by default.
    N: See apt-secure(8) manpage for repository creation and user configuration details.

**Comment by ahsath** [comment]
Same

**Comment by KTM888** [comment]
same here

**Comment by brainchild0** [comment]
It seems that the last round of builds populating the PPA  occurred before for the release of Ubuntu 20.04. Building the current release and supporting the _Focal_ target for ongoing releases seems to be an important feature request for everyone in the Ubuntu sphere.

**Comment by babluboy** [comment]
Apologies for the late action - been a bit diverted away from Bookworm.
I have now included both Focal and Groovy into the daily and stable builds - have started the builds for groovy and focal, will update back when the builds have finished sucessfully

**Comment by babluboy** [comment]
The build has completed successfully for both the daily and stable repos. Please report back if you are still facing issues:

https://code.launchpad.net/~bablu-boy/+recipe/bookworm-gh-stable
https://code.launchpad.net/~bablu-boy/+recipe/bookworm-gh-daily

**Comment by brainchild0** [comment]
So users currently updating from `bookworm-team/bookworm` should switch to `bablu-boy/bookworm-gh-stable`? What is the intended difference?

**Comment by babluboy** [comment]
@brainchild0 The codebase is the same - and bookworm-team/bookworm was the earlier repository which is also built by the same receipe. So users can continue to update from the same.

https://launchpad.net/~bookworm-team/+archive/ubuntu/bookworm

**Comment by brainchild0** [comment]
I understand the principle of both archives holding the same build artifacts, but the `bookworm-team` has not been populated with the new ones, so Focal users would have to switch from it unless you also would update it.

I'm not sure I fully understand the comment,  though. Are you deprecating one of the archives?

**Comment by babluboy** [comment]
Ys, just rechecked. it looks like the build has finished but it takes some time for launchpad to populate the new builds for Focal and Groovy. bookworm-team will continue to hold the stable builds (when i do a release on Github) and the daily-build package is built when ever I work on the code.

![Screenshot 2020-06-28 at 3 57 34 PM](https://user-images.githubusercontent.com/14061478/85944972-278c7b00-b958-11ea-9a7c-5f5737e61d4b.png)

**Comment by babluboy** [comment]
looks all good now, the packages for Focal and Groovy have been published.

![Screenshot 2020-06-28 at 4 21 05 PM](https://user-images.githubusercontent.com/14061478/85945688-26118180-b95d-11ea-8296-d84da4b503a3.png)

**Comment by brainchild0** [comment]
Ok I see that new artifacts did finally go into the repository, but     one combination still missing, the one  I had been anticipating,    is the short package name `bookworm`.

It seems the various package names, and the several different repositories, in current use are a source of  confusion.

Normally, packages in Debian repositories use short names, just long enough to identify them over other packages. If for some reason two package names must be offered that provide the same software, then one would be a metapackage, empty of any installed content, but giving the other as the dependency.  Such conventions prevent redundancy or collisions.

The best approach would appear to me to  build from the source into a package called `bookworm`,  and then to create further metapackages,  if it  remains necessary for some reason  to support any further naming system.

The use of multiple repositories would not seem to be a clear problem, but seems to create both to confusion and overhead,  perhaps without comparable gain.

**Comment by pixelglade** [comment]
I keep getting this error when running sudo apt update:
`Err:48 https://ppa.launchpadcontent.net/bookworm-team/bookworm/ubuntu jammy Release
  404  Not Found [IP: 185.125.190.80 443]
Reading package lists... Done                                            
E: The repository 'https://ppa.launchpadcontent.net/bookworm-team/bookworm/ubuntu jammy Release' does not have a Release file.
`
