### ISSUE TITLE
About Dialog not appearing properly

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#33]
The About Dialog is coming up as a grey transparent box with a white spinner in the middle...

**Comment by babluboy** [comment]
Screen shot of the incorrect appearance of the About Dialog
![about dialog issue](https://cloud.githubusercontent.com/assets/14061478/25180171/ea2e962a-2504-11e7-9b37-d023b3fec2f4.jpeg)

**Comment by babluboy** [comment]
@Philip-Scott
Hi...would you have any clue as to why the About dialog will come up this way? Weird thing is that when I build from source, for some time the About dialog comes up properly. In my other app Nutty, this does not happen and have compared the code of the two apps but cant spot the issue.

Appreciate you are busy and sorry for tagging you on this - but will be great help if you can provide pointers on what would cause this.

**Comment by cassidyjames** [comment]
@babluboy we think we tracked this down to being an outdated version of Granite used for the build, we were seeing it in all apps submitted to AppCenter as well. @Philip-Scott might have more info, though.

**Comment by babluboy** [comment]
@cassidyjames and @Philip-Scott good to know that I'm not alone :-). Any suggestions to resolve the issue? I tried looking at [Noise CMakeLists ](https://github.com/elementary/music/blob/master/CMakeLists.txt) and in the dependencies it mentions just "granite". I have done the same for Bookworm. Do I need to mention a specific granite version for this to work correctly.

**Comment by cassidyjames** [comment]
@babluboy it looks like this was fixed in AppCenter, so you should be good to close this out.

**Comment by babluboy** [comment]
@cassidyjames Verified this in a fresh VM where the issue was present ...the About dialog appears correctly upon installing bookworm from Appcenter beta...steps to resolve the bug:
1- sudo apt remove bookworm (if bookworm is already installed)
2- install new appcenter beta by building from source with required libraries per instructions on https://github.com/elementary/appcenter
3- Add supporting repository by running the following commands in sequence:
    a) wget -qO - https://packages.elementary.io/key.asc | sudo apt-key add -
    b) sudo apt update && sudo apt install software-properties-common --no-install-recommends
    c) sudo add-apt-repository https://packages.elementary.io/appcenter
    d) sudo apt update
4- restart machine and open appcenter and install bookworm

However, not sure how to fix the issue for people who install from the launchpad PPA.
