### ISSUE TITLE
[Feature] Crazy idea to launch bookworm in a weird way

### ISSUE THREAD

**Issue by Libervurto** [babluboy/bookworm#336]
Launch by typing
`$ bookworm`
instead of
`$ com.github.babluboy.bookworm`
😮😮😮😮😮

Why did you do this?  You chose a nice name "bookworm" and then use this horrible "name" to launch it.  WHY?
I have aliased it until you stop being a mad person. :stuck_out_tongue_closed_eyes:

**Comment by axonotics** [comment]
@Libervurto When I started Bookworm, I had named the package boomworm nice and simple as you mention. However, Elementary OS recommends the reverse-DNS scheme for apps published in AppCenter as per the standards here:
[https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic)

I have got a bookworm package on Launchpad which also gets build from the same source code, but not sure if it is built for all of the packages lately.
[https://code.launchpad.net/~bablu-boy/+archive/ubuntu/bookworm-daily/+packages](https://code.launchpad.net/~bablu-boy/+archive/ubuntu/bookworm-daily/+packages)


Hopefully that answers the query.

**Comment by babluboy** [comment]
@Libervurto When I started Bookworm, I had named the package boomworm nice and simple as you mention. However, Elementary OS recommends the reverse-DNS scheme for apps published in AppCenter as per the standards here:
[https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic](https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-id-generic)

I have got a bookworm package on Launchpad which also gets build from the same source code, but not sure if it is built for all of the packages lately.
[https://code.launchpad.net/~bablu-boy/+archive/ubuntu/bookworm-daily/+packages](https://code.launchpad.net/~bablu-boy/+archive/ubuntu/bookworm-daily/+packages)

Hopefully that answers the query.
