### ISSUE TITLE
Can't install on pop_os, syntax error

### ISSUE THREAD

**Issue by ludrol** [babluboy/bookworm#359]
`
Setting up bookworm (1.1.2+git20200823-1) ...
  File "/usr/share/com.github.babluboy.bookworm/scripts/mobi_lib/mobiml2xhtml.py
", line 249
    print "     - fixed by injecting empty start tag ", tname
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("     - 
fixed by injecting empty start tag ", tname)?

dpkg: error processing package bookworm (--configure):
 installed bookworm package post-installation script subprocess returned error e
xit status 1
Errors were encountered while processing:
 bookworm
E: Sub-process /usr/bin/dpkg returned an error code (1)
`
 I am on Pop!_OS 21.04 x86_64 
kernel: 5.11.0-7620-generic

**Comment by ludrol** [comment]
it broke whole apt package manager. Now i can't install anything nor uninstall

**Comment by babluboy** [comment]
Thanks for raising this issue. I thought I had fixed the python 2 to python 3 issue - python 3 needs parentheses for print...

even more strange is that it broke the package manager, people had installed bookworm fine for PoP OS...hopefully someone with pop os can comment on this issue...
I will keep it open, if you get a resolution please update for the benefit of others
