### ISSUE TITLE
meson.build:2:0: ERROR: Could not execute Vala compiler "valac"

### ISSUE THREAD

**Issue by rollto** [babluboy/bookworm#389]
after command  :  meson build --prefix=/usr
meson.build:2:0: ERROR: Could not execute Vala compiler "valac"

**Comment by rollto** [comment]
sudo apt-get install libgtk-3-dev

**Comment by jbicha** [comment]
Does this help?

`sudo apt install valac`

**Comment by babluboy** [comment]
Hi all, thanks for your contributions to the patches and help for compiling bookworm as a standalone application. However to indtall bookworm from app stores and software hubs i have to rely on a build system luke meson. 

At the moment I am focusing on upgrading to all the latest libraries like Gtk4, Granite7, Gee0.8 etc. This is requiring me to do a lot of code changes as many api are replaced in gtk4. I should be able to work my way through and update bookworm to the latest versions in a week and update back.

But this is a good issue to track how to compile bookworm as a standalone app. If all the suggestions here work then I would use this approach to update the bookworm website accordingly.
