### ISSUE TITLE
Unable to install on Kali linux

### ISSUE THREAD

**Issue by suranands** [babluboy/bookworm#395]
## My current setup
```sh
$ lsb_release -a                               
No LSB modules are available.
Distributor ID: Kali
Description:    Kali GNU/Linux Rolling
Release:        2024.1
Codename:       kali-rolling
```

##PPA:Bookworm-team/bookworm Error
```sh
E: The repository 'https://ppa.launchpadcontent.net/bookworm-team/bookworm/ubuntu kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

##PPA:Elementary-OS/stable Error
```sh
E: The repository 'https://ppa.launchpadcontent.net/elementary-os/stable/ubuntu kali-rolling Release' does not have a Release file.
N: Updating from such a repository can't be done securely, and is therefore disabled by default.
```

##Errors while trying to build from source
```sh
$ sudo apt install unzip unar python2 libgtk-3-dev libgee-0.8-dev libxml2-dev libgranite-dev webkit2gtk-4.0 libwebkit2gtk-4.0-37 libsqlite3-dev poppler-utils libpoppler-glib-dev html2text curl meson valac appstream gettext ninja 
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
E: Unable to locate package webkit2gtk-4.0
E: Couldn't find any package by glob 'webkit2gtk-4.0'
E: Unable to locate package ninja
```

Look forward to any help please. Thank you.

**Comment by agilous** [comment]
I was able to resolve this issue on Ubuntu 24 LTS with: `sudo apt-get install libwebkit2gtk-4.0-dev`

Hope this may be of some help.

**Comment by LuckyLuc96** [comment]
I would recommend using flatpak to install this on non-debian systems. I use an offshoot of Ubuntu and installed with flatpak, and it also installed the needed dependencies. 

1) Install flatpak 
sudo apt install -y flatpak
sudo flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

2) Install bookworm
flatpak install bookworm

**Comment by babluboy** [comment]
Thanks @agilous and @LuckyLuc96. Hopefully the workarounds you have suggested have allowed bookworm to run on kali Linux. Please reopen if the issue still persists. I'm upgrading bookworm to GTK4 so hopefully it will be a better experience
