### ISSUE TITLE
Add a List View to Bookworm

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#44]
It will be difficult for scrolling through a large number of books in cover view mode. So the following needs to be done:
1. Create a ListViewMode to list books by columns. Title and show other metadata like Author, Date Added to Library can be the columns. Sorting on each columns should be present. This can be like Noise ListView...
2. Paginate the Cover Image view to limit the number of covers to around 20 and show the latest read / added books first. The pagination view can be like slingshot...

**Comment by babluboy** [comment]
First version of the Library List view completed...while this may not look as pretty as the one with the cover images, it will to quickly scroll through the library and sort books by metadata...The filtering via the search also works to short list the items...books can be opened by double clicking a row...

Few more things to implement on the list view like the right click on a row to bring up the context menu, making changes to the book metadata (via the context menu) immediately reflected on the list, etc...

![library list view](https://cloud.githubusercontent.com/assets/14061478/26446130/bf1c8b5c-413a-11e7-8ba5-0665648f86df.jpeg)

**Comment by Philip-Scott** [comment]
One thing we did on the official Photos app was actually to get rid of the rating system. Since it's local data anyways, most users don't really rate their images (books in this case) 

what would be useful though is to be able to just star or unstar a book :) something like Favorites

**Comment by babluboy** [comment]
Agree...maybe people can use the rating as favourite...by default books don't get a rating so giving a rating can mark the book as a favourite...ratings can also be filtered using the list view

**Comment by babluboy** [comment]
List View completed with the options to select multiple books for deletion similar to the grid view...sorting and filtering is also enabled on the list view...
![library list view](https://cloud.githubusercontent.com/assets/14061478/26678078/b02e5b0c-46c6-11e7-9e59-a4172829b124.png)
