### ISSUE TITLE
Remember last state

### ISSUE THREAD

**Issue by Philip-Scott** [babluboy/bookworm#5]
As per elementary Human Interface Guidelines, you should make your app remember the state it was left on. This includes:

- Window size
- Window state (fullscreen?)
- Current book opened
- Remember the page you're on, per book (You can make use of your database for this)  

For the things not on the dabatase, you can use GSettings to save them :)

**Comment by choyan** [comment]
On the additional point, have a progress bar below the book cover.

**Comment by babluboy** [comment]
Pushed a code update which "remembers" the last page read for a book. iBooks takes the reader directly to the last read page of a book without giving a chance to the user to see if the user wants to continue reading the same book or a different one. I like the feature sometime but find it annoying sometimes where I have to comeback into the library view and then select another book to read. I have not implemented the "direct to last read page", lets see what people like...let me know your thoughts....

**Comment by babluboy** [comment]
Will see how to use GSettings to save window size and perhaps other settings later like the colour profile, font size, etc.

**Comment by Philip-Scott** [comment]
@babluboy Granite has a Settings class which makes interacting with GSettings super easy :) 

https://github.com/Philip-Scott/Notes-up/blob/master/src/Services/Settings.vala

https://github.com/Philip-Scott/Notes-up/blob/master/src/Widgets/Window.vala#L160

**Comment by babluboy** [comment]
@Philip-Scott Many thanks for the quick response, should fix the GSettings quickly

**Comment by babluboy** [comment]
@choyan The progress bar for each book is a bit different to this Issue about remembering the state of the app. I have added a separate Issue (#12) to track the same

**Comment by babluboy** [comment]
@Philip-Scott Have pushed updates to save the widow size, maximized state, last page read for each book. The last book read is also saved, however I have not taken an action to open the last book read automatically yet. Lets see what people say on that before I make changes. This change is also pushed to the PPA.
