### ISSUE TITLE
Remove "for elementary OS" from appdata

### ISSUE THREAD

**Issue by danrabbit** [babluboy/bookworm#51]
because everything published in AppCenter is for elementary OS. It's a little redundant ;)

**Comment by babluboy** [comment]
@danrabbit Agree. I have reworded the description to the following. Will be good to get a review from you on the wording before committing on GH.
`<p>
      A simple reader focussed eBook application.The goal of Bookworm is to provide a uniform user experience for multiple electronic document formats like epub,pdf, mobi, cbr, etc.
    </p>` 
    ` <p>
      Bookworm is currently under active development and only the EPUB format is supported in this version. PDF support will be added to the next version.
    </p>`

**Comment by cassidyjames** [comment]
That's better! You could also likely not use the word "application" because everything in AppCenter is an application.

Something like: 

>A simple, focused eBook reader

might be a little more concise.

**Comment by babluboy** [comment]
@cassidyjames Thanks for the input. Agree with your suggestion. Will make the change accordingly.
I will gear up for more meaty design suggestions to improve the look and feel of Bookworm.
