### ISSUE TITLE
Screenshot points to non-existent file

### ISSUE THREAD

**Issue by danrabbit** [babluboy/bookworm#52]
The screenshot in the AppData points to a file that doesn't exist anymore. Should update that :)

Also, you should use the `raw` subdomain as in `https://raw.githubusercontent.com/babluboy/bookworm/master/screenshots/...`

**Comment by babluboy** [comment]
@danrabbit Many thanks for the review and pointing this issue. I was not aware of the raw domain. The screen shots look bigger and better on the raw domain.
I have put two screen shots - the Library view and the Reading view. Is that ok or should I just stick to one screen shot to be aligned to AppCenter standards.

`<screenshot type="default">
          <caption>Bookworm Library View</caption>
          <image>https://raw.githubusercontent.com/babluboy/bookworm/master/screenshots/BookwormLibraryView.jpeg</image>
      </screenshot>`

`<screenshot type="default">
          <caption>Bookworm Reading View</caption>
          <image>https://raw.githubusercontent.com/babluboy/bookworm/master/screenshots/BookwormReadingView.jpeg</image>
      </screenshot>`

Also will be good to get you review on the screen shots:
[Library View](https://raw.githubusercontent.com/babluboy/bookworm/master/screenshots/BookwormLibraryView.jpeg)
[Reading View](https://raw.githubusercontent.com/babluboy/bookworm/master/screenshots/BookwormReadingView.jpeg)
