### ISSUE TITLE
Use placeholder text for search entries

### ISSUE THREAD

**Issue by cassidyjames** [babluboy/bookworm#53]
I noticed you're using the `text` property for your GTKSearchEntry, but `placeholder-text` is what you want. :)

**Comment by babluboy** [comment]
Thanks for this ...didn't even know this property existed ! ...Could have avoided a lot of logic to clear the text on focus...anyways good to learn something...will make the changes and close this...

**Comment by babluboy** [comment]
Removed all logic to replace placeholder text with blanks on focus of the searchentry widget.
