### ISSUE TITLE
Use the system's Webkit

### ISSUE THREAD

**Issue by Philip-Scott** [babluboy/bookworm#6]
Is there a reason you're specifically using `ppa:webkit-team/ppa` instead of the one that's included with the system? If not, you should consider using the default one instead :)

**Comment by babluboy** [comment]
ppa:webkit-team/ppa was mentioned by mistake, the code does not require this ppa to be installed and works fine with default webkit on elementary. I have updated the README file to remove the ppa:webkit-team/ppa from the installation instruction.
