### ISSUE TITLE
Ampersand in title of book causes fatal errors

### ISSUE THREAD

**Issue by ddombrow** [babluboy/bookworm#61]
Got multiple fatal error trying to open my book with local file name: 
"The_Little_Elixir_&_OTP_Guidebook.epub"

Ampersands killed it.  Opened a PR to just URI decode the file name but not Html decode:
https://github.com/babluboy/bookworm/pull/60

**Comment by babluboy** [comment]
@ddombrow Many thanks for spotting this one and debugging the code to spot the issue as well...I was working on the code so will check and merge it later today...None of my books had special chars in the name so didn't spot the issue. 
Need to check if the code handles all special chars in the file name
Need to go through and handle this and other conditions to avoid crashes (show user friendly warnings)

**Comment by babluboy** [comment]
Have fixed the issue...looks like an unnecessary call to Pango markup was causing the issue with ampersands. Soup.URI.decode seems to handle the escape chars properly...let me know if you still have the issue...

**Comment by ddombrow** [comment]
:+1:  confirmed fixed on the master branch thanks
