### ISSUE TITLE
Full Screen Mode for Reading

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#63]
Kaloyan Genkov provided the following enhancement request on [this](https://plus.google.com/u/0/108373005915819607337/posts/SvSF4MbgRWj) Google Plus thread:

Can a  full screen option be chosen for Bookworm ?

**Comment by uncertainquark** [comment]
A full screen mode would be nice, yes.

**Comment by babluboy** [comment]
Full screen option implemented with the following choices:
1- F11 key will make the Reading view go full screen
2- Esc key will exit from full screen
3- Left click context menu on reading view enables full screen
4- Left click context menu on full screen view will exit from full screen

On full screen view the header and footer bar are hidden, navigation is only possible with forward/backward arrow keys. 
![fullscreenview](https://cloud.githubusercontent.com/assets/14061478/26173625/6d5249ac-3b44-11e7-82bf-95da6f5e5907.jpeg)
Probably I can work later to enable page navigation by right click near the left and right edge
