### ISSUE TITLE
Reading Modes : Normal, Solarized, Night

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#64]
Kaloyan Genkov provided the following enhancement request on [this](https://plus.google.com/u/0/108373005915819607337/posts/SvSF4MbgRWj) Google Plus thread:

Also, I see there is a "night mode" but it is actually an inverted mode (dark background, white font. I suggest two things:
1. Rename the night mode to dark mode and create a new night mode, having a reddish white as a background colour. (see http://jonls.dk/redshift/ for the reasoning)
2. Use the dark Solarized theme for the dark mode http://ethanschoonover.com/solarized

**Comment by uncertainquark** [comment]
A non-Solarized dark theme like Dark Grey or a Black background would be appreciated. Solarized light/dark feel very heavy on my eyes.

Maybe just use the same dark background color which elementary OS itself use and your app titlebar uses too?

**Comment by babluboy** [comment]
@uncertainquark At the moment for the dark mode I'm using `style.color='black'`
Do you have a specific hexcode for the dark colour in mind. Since the usual choice is limited to three - Light, Sepia and Dark - I'm thinking of the same as well. However, I can provide a handle for the user to set any specific color via a exposed css file ?

**Comment by uncertainquark** [comment]
I would like either the default elementary Dark color as in the titelbar here:

![screenshot from 2017-05-16 10 30 40](https://cloud.githubusercontent.com/assets/22585732/26090475/db6eb9c0-3a22-11e7-8883-0edf6862605a.png)

Or a Dark Grey like #222222 which is really soothing to the eyes.

**Comment by m-delvalle** [comment]
For dark background I like the Monokai background: #272822. Combined with a light grey font it looks easy on the eyes, I think. Something like #BFBFBF for the fonts.

**Comment by babluboy** [comment]
And this is how the current dark mode looks with `backgroundColor='black'`
![existing dark mode](https://cloud.githubusercontent.com/assets/14061478/26107336/d72144fa-3a40-11e7-8f98-fe5dd8932a63.jpeg)

This is how it looks like with `backgroundColor='#272822'` and `color='#BFBFBF'`
![changed font and bg color](https://cloud.githubusercontent.com/assets/14061478/26107343/dbd07a2a-3a40-11e7-8338-316fa05cddec.jpeg)

I can spot the slight change with the new background and font color and it feels pretty easy on the eyes to me (although I'm not a expert at color options !)...I can go with this for the Dark Profile setting and perhaps expose it through the CSS file for others to play around for their suitability.... 

Would you have a suggestion for the Light Profile setting - At the moment I have just got background-color: white; and font color as default black

**Comment by babluboy** [comment]
Finally settled on three modes: White, Sepia and Dark.
The dark and sepia are from solarized theme for [Jekyl](https://gist.github.com/qguv/7936275) and the white is from the iPhone.

White: `backgroundColor='#fbfbfb' | style.color='#000000'`
![white](https://cloud.githubusercontent.com/assets/14061478/26118755/ea78808c-3a62-11e7-9434-2203ec317d3f.jpeg)

Sepia: `backgroundColor='#fdf6e3' | color='#586e75'`
![sepia](https://cloud.githubusercontent.com/assets/14061478/26118761/f106821e-3a62-11e7-86fb-9732108e91e7.jpeg)

Dark: `backgroundColor='#002b36' | color='#93a1a1'`
![dark](https://cloud.githubusercontent.com/assets/14061478/26118766/f798662e-3a62-11e7-8f0b-8f5b75039c28.jpeg)

Let me know your views

**Comment by uncertainquark** [comment]
Thank you for the considerations. Sepia looks quite good :)

Though a dark mode which is not Solarized would really be appreciated. Dark Grey (#222222) or pure black. Its okay if it is optional or can be set manually. I like Dark modes for reading at night, but Solarizd Dark Blue just feels too heavy for long reading.

**Comment by babluboy** [comment]
@uncertainquark I have opened #72 to support user customization of the three reading profiles

**Comment by babluboy** [comment]
Added a new issue #73 to track the functionality of a night mode using red shift

**Comment by m-delvalle** [comment]
Sorry about the delay :stuck_out_tongue: 

> This is how it looks like with backgroundColor='#272822' and color='#BFBFBF'

I'm seeing both bluish backgrounds (very subtle difference, wouldn't dare suggest such nit-picking-ish change :wink: ), but that's not the color code I intended to suggest:

[Google color picker #272822](https://www.google.com.ar/search?q=%23272822)
#272822 would be rgb(39, 40, 34), which should be a certain shade of gray.

Anyways, with the new [Preferences dialog](https://github.com/babluboy/bookworm/issues/72) coming down the pipeline, this is no longer relevant :+1:
