### ISSUE TITLE
Open with support

### ISSUE THREAD

**Issue by Philip-Scott** [babluboy/bookworm#7]
If you could open ebooks right from your file manager into the app it would be awesome! 

Bonus points: If the book you opened was already added before, and you were on a certain page, open it on that page

**Comment by babluboy** [comment]
Completed open-with-support by adding a contractor to Files. The following behavior is done:
1- Select multiple epub files, right click and "Open in Bookworm" - the epubs which are not in the library are added to the library
2- Double click and epub (or select one epub and Open in Bookworm) - the epub is added to bookworm and the reading mode is opened for that epub. If the epub is already in the library then the last opened page of the book is shown
![bookworm - open with](https://cloud.githubusercontent.com/assets/14061478/24221379/06acbd60-0f46-11e7-8786-144009e77952.jpeg)

**Comment by babluboy** [comment]
@choyan Will be great if you can test this feature

**Comment by choyan** [comment]
@babluboy everything is working great. 
The about page is not showing properly from the very beginning. Please check that out.

**Comment by babluboy** [comment]
@choyan yes, I have also noticed the about dialog showing as a ghost in my VM where I just install from PPA...however it shows up fine on my laptop where I build from source...do you install from PPA or build from source?
I will open another issue to track this
