### ISSUE TITLE
Zooming ability

### ISSUE THREAD

**Issue by lecroix74** [babluboy/bookworm#75]
there needs to be added zooming/fit page ability. without it it is basically unusable

**Comment by babluboy** [comment]
@lecroix74 thanks for raising the issue. The zooming function is already available as part of the font zooming - it zooms images as well. Did you try that in the pop up menu in the reading view ? Do let me know if it did not work for you in some way.

I have already completed the page fit as part of the v0.7 version which I will release on Appcenter shortly. This will allow the user to customize the line width and the line height as well.

Here is a screen shot of the reading controls - zooming, content adjustment and color profile
![reading controls](https://cloud.githubusercontent.com/assets/14061478/26204728/83c220c0-3bd7-11e7-9dcd-1f3165acb92e.jpeg)

**Comment by choyan** [comment]
Can the same functionality be implemented with shortcut key? Like 'Ctrl' + '+' for Zoom-in and 'Ctrl' + '-' for Zoom-out.

**Comment by babluboy** [comment]
@choyan yes...those shortcuts seem a good idea

**Comment by babluboy** [comment]
Control + plus key and Control + minus key shortcuts implemented for zoom in and zoom out respectively
