### ISSUE TITLE
Log in with google.

### ISSUE THREAD

**Issue by cairin** [babluboy/bookworm#78]
For play books native download. As apposed to going to their website and having to download each book and then import them to your app. 

Ideally sync with play books so location tracking is enabled. (Not sure if you can actually do this though)

**Comment by babluboy** [comment]
@cairinmichie thanks for opening the issue. This is similar to one on #30 where another user has asked to integrate with LibraryThing. I agree that it will be nice to have direct integration with large book stores like Google, Project Guttenburg, etc to search, pull in free books and read them locally. I definitely would like to add this feature when the fundamental stuff pending is done like extending support for Kindle Books (.MOBI), a list view for the library, etc...hopefully I can find a way to integrate with these book stores :-)

**Comment by babluboy** [comment]
@cairinmichie I forgot to ask how bookworm is able to work with books downloaded from Google Play ...is it able to open epubs fine or do you download them in PDF format...in my opnion epubs will work best...let me know if you are seeing any issues with books from google play...

**Comment by cairinmichie** [comment]
@babluboy No rush, I'm sure you're super busy getting things of the ground. I will possibly be able to help out in a month or two when I have free time :)

Google play uses the epub file format, and you can choose to download them as pdf or epub (epub obviously better).

At the moment I use [calibre](https://calibre-ebook.com/) to convert any books between formats - they support hundreds. [Here](https://github.com/sethvincent/ebook-convert) is a javascript wrapper (of their command line tool) - I'm sure you could port this if needed to your language of choice.

Hope this helps :)
