### ISSUE TITLE
Welcome screen on empty library

### ISSUE THREAD

**Issue by Philip-Scott** [babluboy/bookworm#8]
Have a quick and easy way to start reading when a user first opens their app :)

This can easily be done using Granite.Widgets.WelcomeScreen

![screenshot from 2017-02-18 13 50 34](https://cloud.githubusercontent.com/assets/10786508/23096400/0a9bb0ba-f5d9-11e6-9d4b-7884ed9e4d18.png)

**Comment by babluboy** [comment]
Added the Granite Welcome message for the scenario when the user opens Bookworm and has no books in the Library. This can be for the first time the application is open or for any time the application is open and there are no books in the library i.e. all books deleted from the library.
A Open Folder widget is provided to allow the user to be able to select an eBook.
![bookworm-welcome screen](https://cloud.githubusercontent.com/assets/14061478/23105517/837a4f6e-f6d8-11e6-81c7-f16d7b5bd211.jpeg)
