### ISSUE TITLE
Use GResources

### ISSUE THREAD

**Issue by tintou** [babluboy/bookworm#81]
It would be a nice move to use GResource to embed all the custom icons & CSS into the executable allowing faster execution time and better portability

**Comment by babluboy** [comment]
@tintou Many thanks for this suggestion - I was not aware of GResource. While Bookworm is a single instance implementation and there no scope for resource sharing between instances, it is still a good idea to see if it makes the execution faster...will use this issue to track it...

Would you have a sample vala application code using GResource ...may be an Elementary app using GResource...will help me pick it up quicker :-)

**Comment by bil-elmoussaoui** [comment]
@babluboy you can take a look at the source code of FeedReader :)

**Comment by babluboy** [comment]
Added icons and javascript files to executable gresource
