### ISSUE TITLE
when the file name has a # then the images inside the book are not displayed properly.

### ISSUE THREAD

**Issue by XarisA** [babluboy/bookworm#83]
Tested on cbz/cbr, epub and pdf. 
This could be a problem for someone having a big organized collection, and having "#" instead of "number" is common I think.
Thanks in advance.

**Comment by babluboy** [comment]
@XarisA - Thanks for raising the issue. However I was not able to reproduce the issue - I renamed one of my epubs to "Don Quixote #Guttenburgh.epub" and bookworm was able to open it fine (unless I have done some fix in 0.8 - which I doubt)
Can you let me know the name and directory structure of your book and also try running bookworm from the command line in debug mode "bookworm --debug" and put the error messages when you try opening the book with the "#" in file name

**Comment by babluboy** [comment]
@XarisA I now see what you mean, when the file name has a # then the images inside the book are not displayed properly and appear like the screen shot below...I have been able to reproduce the issue and should be an easy fix...
![screenshot from 2017-05-23 22 27 44](https://cloud.githubusercontent.com/assets/14061478/26377242/65d30294-4007-11e7-80b7-ef2af3f1c211.jpeg)

**Comment by babluboy** [comment]
When i encode the # to %23 the images are displayed fine - will add a fix to encode characters for paths to images and resources....
