### ISSUE TITLE
Crashing and very slow or no loading at all.

### ISSUE THREAD

**Issue by dcharles525** [babluboy/bookworm#84]
I recently added some books to my library but the problem is the previews don't show up and when I click on a book, it sometimes crashes. Here is a screen shot of the preview problem.

![screenshot from 2017-06-02 15 19 21](https://cloud.githubusercontent.com/assets/4961680/26741421/487b6248-47a7-11e7-8d58-082e8d563217.png)

And here is the output of the crash error:
**
ERROR:arraylist.c:967:gee_array_list_real_get: assertion failed: (index < _size)
Aborted (core dumped)

**Comment by babluboy** [comment]
Many thanks for raising the issue...I have seen the same error happen when I tried loading a book which could not be parsed and this resulted in the code removing the existing cover images of the books (resulting in default covers)...i am working on putting in error handling in the current release so this does not happen...are you able to pin point it to a specific book which causes this...and if possible can you share the book (i.e. if it is not proprietary)....hopefully I should be able to push the fix by next week as part of v0.8...

**Comment by babluboy** [comment]
Will be great if you can spot a way to recreate the issue - one way to come out of the issue is to remove the books from the library (your ebook files will not be deleted) and re-add them back in...

**Comment by babluboy** [comment]
@dcharles525 Thanks. I will issue the fix and update this when the same is completed and released
