### ISSUE TITLE
Directly go to last read book (Skip Library View)

### ISSUE THREAD

**Issue by pedropacheco92** [babluboy/bookworm#85]
Is possible to open when you left off after you close the app?

**Comment by babluboy** [comment]
@pedropacheco92 I have thought about this option but did not implement it as it sometimes is a bother to return back to the library if you want to read another book. The book read last is always placed at the top in the library for easy access to open...

But now that you have asked for this, does it make sense to add this as a preference ?

**Comment by pedropacheco92** [comment]
Yes, it would be very nice! It's very frustrating to open a book after you read it and it is not where you left off, and you must be scrolling a lot to find.

**Comment by babluboy** [comment]
Ok...there are two issues here:
1- Go straight into the book last read when bookworm is opened (library view is skipped). This should happen if bookworm was closed while I'm reading view.

2. When a page is opened. It should open at the exact position where it was left off. This is to avoid scrolling

I will open another issue to track the second issue. This issue can track the first one.

**Comment by pedropacheco92** [comment]
Nice, thanks!

**Comment by babluboy** [comment]
Pushed the update for adding a preference on whether to show library view at start. If this is turned off (default) then the user is shown the reading view of the book last read at the last read page and position (auto scrolled vertically).

If the preference to show library view on start is turned on, then the library view is always shown at start and the user has to click on a book to go into reading mode. If the book was being read previously, then the page and position last read is opened.

If bookworm was closed in the library view then this preference setting has no effect and the library view is shown on start. 

![screenshot from 2017-07-12 00 12 51](https://user-images.githubusercontent.com/14061478/28094964-ae40828e-6697-11e7-8f79-ca8de89fb536.png)
