### ISSUE TITLE
Open page at last reading position

### ISSUE THREAD

**Issue by babluboy** [babluboy/bookworm#86]
On opening a previously read book the page should scroll down to the last read position.
This issue is created from the comments in issue #85

**Comment by babluboy** [comment]
Completed adding code to set the last read page position in two scenarios:
1- When the "Return to library" button on the header is clicked to exit a book
2- When the application is closed in reading view

The scroll to the last recorded position is applied only once when the book is opened by:
1- Selecting the book for reading in the library
2- Opening a book in File Explorer using Bookworm and the book is already present in Bookworm's library

**Comment by jacksonbenete** [comment]
When you "check word meaning" and then "resume" the app lose the last reading position which is really annoying.
Should the dictionary text of the function be displayed in a pop-up or something instead of moving the reader to another window view?

**Comment by jacksonbenete** [comment]
You will also lose the last reading position when adjusting reading preferences other than font size.

**Comment by babluboy** [comment]
@jacksonbenete Thanks for the time to open this issue. Definitely agree with you. 

The reason I have got Word Meaning open in the info section is to expand the details in the future to include Wikipedia and also preferences to use a local dictionary when no internet is present

Both preferences and word meaning should return to the last read position when the page loads. Should not be hard to use the same logic when re-opening Bookworm to continue reading.
