### ISSUE TITLE
[Request] Add Mobi support

### ISSUE THREAD

**Issue by btd1337** [babluboy/bookworm#87]
Is it possible u add a .mobi support?

**Comment by babluboy** [comment]
@btd1337 Yes definite...once I push the current UX improvements this weekend to Appcenter, my plan is to add .mobi support

**Comment by babluboy** [comment]
Pushed a update to add .mobi support. Used 7zip extract to decompress .mobi and the processing is exactly the same as ePuB. More testing is required on a number of MOBI and PRC files available for download...

**Comment by babluboy** [comment]
Looks like many .mobi donot have an ePub equivalent compressed in the file...7zip does not work in this scenario...

Looking at the python utility mobi_unpack.py which seems to work and extract the mobi content to a HTML format...

**Comment by babluboy** [comment]
Pushed the first version of code using mobi_unpack.py and so far it is working well with the MOBI books I could download for testing...
The key work now is to break the single html file in the mobi bundle into chapters to make the reading experience consistent with other formats...

**Comment by babluboy** [comment]
Added the code to split up the single mobi unpacked html file into smaller chapter based html content. This is now uniform with the rest of the formats handled in bookworm. Closing the mobi support issue now, as the code is working properly with several files pulled from internet.
