### ISSUE TITLE
Ctrl + `+` zoom in is not working

### ISSUE THREAD

**Issue by choyan** [babluboy/bookworm#90]
I can zoom out with ctrl + `-`.  But can't zoom in with Ctrl + `+`

**Comment by babluboy** [comment]
@choyan Since to get + we have to press Shift, the zoom-in short cut will be Ctrl + Shift + '+'
Let me know if that works. I should probably update the tool tip on the right click menu to clarify this.

Let me know if Ctrl + Shift + '+'

**Comment by choyan** [comment]
Yes. It's working with ctrl + shift + '+'

**Comment by babluboy** [comment]
Thanks for the update. I have updated the tool tip on the zoom-in to mention Shift key .....closing this issue
