### ISSUE TITLE
version 0.8.0 fails to build with vala 0.36+

### ISSUE THREAD

**Issue by decathorpe** [babluboy/bookworm#91]
I get the following error when trying to compile the new version on fedora:

```
/builddir/build/BUILD/bookworm-0.8.0/src/library.vala:444.59-444.73: error: Argument 1: Cannot pass value to reference or output parameter
				BookwormApp.AppWindow.library_table_liststore.remove (iterToBeRemoved);
```

I think you'll have to wrap this line in a conditional macro; other elementary projects fixed this error that way too:

```vala
#if VALA_0_36
	BookwormApp.AppWindow.library_table_liststore.remove (ref iterToBeRemoved);
#else
	BookwormApp.AppWindow.library_table_liststore.remove (iterToBeRemoved);
#endif
```

**Comment by babluboy** [comment]
@decathorpe Thanks for raising this issue. I will add in the suggested wrapper to build with Vala 36. I will spin up a VM with vala 36 and compile it to check if that is the only compatibility issue.

**Comment by babluboy** [comment]
Added vala compatibility wrapper [030cc2f](https://github.com/babluboy/bookworm/commit/030cc2f5c55d5ca2f85822fc7cf34e14a81e7511)
