### ISSUE TITLE
Make failing on Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by shinenelson** [babluboy/bookworm#94]
I'm trying to compile bookworm on Ubuntu 16.04 LTS. I get a bunch of warnings at 
```
[   4%] Generating src/main.c;src/bookworm.c;src/utils.c;src/constants.c;src/ePubReader.c;src/book.c;src/database.c;src/settings.c;src/bookinfo.c;src/headerbar.c;src/dialog.c;src/window.c;src/prefpopover.c;src/library.c;src/pdfReader.c;src/contentHandler.c;src/comicsReader.c;src/backgroundTasks.c;src/mobiReader.c
```
 and then the following error on `make`.

```
CMakeFiles/bookworm.dir/build.make:136: recipe for target 'bookworm_valac.stamp' failed
make[2]: *** [bookworm_valac.stamp] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/bookworm.dir/all' failed
make[1]: *** [CMakeFiles/bookworm.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2
```

Is this me doing something wrong?

**Comment by babluboy** [comment]
@shinenelson I have not really built bookworm on 16.04 - Launchpad only gives the option to build from Yaketty (16.10) so perhaps 16.04 is too old...
However,  that said, is the code failing with any specific error like a library not found or a version of a required library not being present. The Error that you have provided comes at the end, but the relevant error should be somewhere higher up...better if you can pipe the whole build output into a file and attach it to this issue - that will give me an idea of where it is failing.

**Comment by shinenelson** [comment]
Oh damn, my bad. Looking at the error log with a larger monitor with a better resolution (pun intended :stuck_out_tongue_closed_eyes:) showed that was an error indeed.

I found the line with the error : 
```
/home/shine/dev/git/bookworm/src/window.vala:143.5-143.60: error: The name `set_allow_universal_access_from_file_urls' does not exist in the context of `WebKit.Settings'
    webkitSettings.set_allow_universal_access_from_file_urls(true); //this gives launchpad build error for Yaketty
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

You were right @babluboy. This could be a thing with ubuntu. The comment on the line makes that clear enough. And if the build fails with Yaketty, it is probably going to fail for Xenial too.

What do you do for Launchpad to make the build pass successfully?

**Comment by babluboy** [comment]
@shinenelson spot on...I should have guessed that, but wanted the log to confirm it.
Surprisingly the build succeeds with Xenial and Zesty somehow. But fails for Yaketty. I have raised a bug on Launchpad for this as well:
[https://bugs.launchpad.net/launchpad/+bug/1683367](https://bugs.launchpad.net/launchpad/+bug/1683367)
 
Webkit2 has this method since = "2.14" as per the Vala documentation and I have included `webkit2gtk-4.0>=2.14.1` in the CMakeLists.txt. But not sure why it fails on Yaketty (same reason for Xenial as well I guess)...two options: either comment the line and compile (links in the Table of Contents will not work) or make sure the webkit version is greater that 2.14 and try...

let me know how it goes...we can perhaps close this as a upstream package bug ?

**Comment by shinenelson** [comment]
> the build succeeds with Xenial and Zesty somehow (same codebase). But fails for Yaketty.

That makes sense since Xenial is an LTS version and Yaketty just [hit EOL earlier this month](http://www.omgubuntu.co.uk/2017/07/ubuntu-16-10-end-of-life).

> make sure the webkit version is greater that 2.14

I've got `libwebkit2gtk-4.0-37 (version 2.16.3-0ubuntu0.16.04.1)`. So that may not be the problem either.

> comment the line and compile

That compiled the code fine. But I hit another hurdle this time around with `make install`.
I think that is out of the scope of this issue. I could file another issue for it, but I'll brief it here anyway.

`make install` tries to create a directory in `/opt` without honoring the `$PREFIX` from line 264 of `cmake_install.cmake`. And without elevated privileges, it just breaks. Is it really necessary to install scripts to a directory that is not in the user's preferred `$PREFIX` directory? And especially when it requires elevated privileges too.

**Comment by babluboy** [comment]
@shinenelson thanks for your comments, I'm learning as I go as well...

Understand your issue with cmake - use `sudo make install` to resolve the issue with /opt directory creation. But I should probably add a $PREFIX for a scripts directory.

The reason for choosing /opt came from here:
[http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html](http://www.tldp.org/LDP/Linux-Filesystem-Hierarchy/html/opt.html)

**Comment by shinenelson** [comment]
I understand that the install would probably complete successfully if I ran it with `sudo` but my intention was to install to a custom directory that does not require elevated privileges. It would be great if you supported that as well.

Do you want me to close this issue and start a new one for the purpose?

**Comment by babluboy** [comment]
@shinenelson Yes, I agree that this might be better discussed in a new Issue. And since I cannot think of how to resolve the issue of the Webkit2 version on Yakkety, we might as well close this issue.

**Comment by shinenelson** [comment]
Very well then. So be it. I'll close this issue and start a fresh one to honor user preference for `$PREFIX` for the scripts.

**Comment by avently** [comment]
@babluboy i can't compile Bookworm too. I use Manjaro. What can i do? Build process stops on 4%. Many errors and warnings

**Comment by babluboy** [comment]
@avently Thanks for giving Bookworm a try. Would you be able to add the build log here for me to take a look just in case I spot something - the usual culprit is the `webkitSettings.set_allow_universal_access_from_file_urls(true);` as sited above. If this is the case then probably you can try commenting out that code and build.

Is PPA an option for you on Manjaro - ppa:bookworm-team/bookworm

**Comment by avently** [comment]
@babluboy
I commented this lines and build was successfull:

https://github.com/babluboy/bookworm/blob/master/src/dialog.vala#L108
The name `set_xalign' does not exist in the context of `Gtk.Label?

https://github.com/babluboy/bookworm/blob/master/src/window.vala#L139
The name `set_allow_file_access_from_file_urls' does not exist in the context of `WebKit.Settings'

https://github.com/babluboy/bookworm/blob/master/src/window.vala#L140
The name `set_allow_universal_access_from_file_urls' does not exist in the context of `WebKit.Settings'

And all the lines that have "reorder_overlay" (16 matches):
https://github.com/babluboy/bookworm/blob/master/src/library.vala
The name `reorder_overlay' does not exist in the context of `Gtk.Overlay?'

PDF not working. I can't even select a PDF file. I don't know is it related to my fixes or not. Epub works fine

**Comment by babluboy** [comment]
@avently Are you using Gtk+-3.0 ? For example the set_xalign looks like a valid method:
https://valadoc.org/gtk+-3.0/Gtk.Label.set_xalign.html

The errors you have mentioned does not come up on elementary OS - so I'm thinking its specific to Manjaro libraries. PDFs depend upon poppler and the pdf2html utility - not sure if they are working on Manjaro...

I'm thinking of creating a snap for bookworm - does Manjaro support snaps ? If not does it support AppImage or something similar.

**Comment by avently** [comment]
@babluboy I installed poppler with pacman and pdf2htmlex with yaourt. PDF works but not so good. Some books wasn't recognozed (because there is no text, only images). Formatting is on initial state of development as i can see. 

I never tried snaps but it is supported. 
I have both GTKs installed - 3 and 2.

**Comment by babluboy** [comment]
@avently Yes, PDF support is very basic. I plan to improve the PDF rendering soon. Not sure why GTK is not working to build correctly, maybe the right version is not being picked. I will update here when I have a snap available, so that you can give it a go.

**Comment by avently** [comment]
@babluboy I don't think people that use arch will use snaps. Snap hard to maintain (some dependencies should be installed) and it's not cool package system. We have AUR for that purpose. 
Why not just release next version with executables in tar.gz? It's easy. Or even better would be to fix this build errors and even AUR package can build your app

**Comment by avently** [comment]
@babluboy hey! I just updated Vala from my old version and build was made succesfully. So the errors was related to Vala. Nothing to worry about:)

**Comment by babluboy** [comment]
@avently Nice to know that Bookworm is building on Manjaro Linux ...will be great if you can post a screen shot to see how it looks like :-)

**Comment by avently** [comment]
Styling of books can be much better in the next versions :)
![alice](https://user-images.githubusercontent.com/7953703/30174991-a0f0696e-9405-11e7-8990-5360578793a9.png)

**Comment by babluboy** [comment]
@avently many thanks for the screen shot...css on Manjaro looks great...only the "library" button is better on elementary os (like a back pointed arrow)...I will add the relevant css as fall back for other distros to get the same look....

Agree there is lot of scope to make the styling better...if you have some ideas you can open an issue and we can track the same ...thanks for your help to make bookworm better...

**Comment by strangel8p** [comment]
For anyone looking to build Bookworm on Ubuntu 16.04, I can confirm that make fails due to lacking vala bindings. Ubuntu has no plans to upgrade Vala for Xenial beyond 0.30.1-1, which dates from before `set_allow_universal_access_from_file_urls` was added to webkit. So the solution is to upgrade vala through a PPA, like [this one](https://launchpad.net/~vala-team/+archive/ubuntu/ppa). Afterwards, Bookworm builds like a charm.
