### ISSUE TITLE
No icons in the header bar

### ISSUE THREAD

**Issue by Anne017** [babluboy/bookworm#97]
There is no icon (grey rectangle with a red parking ban) in my header bar for:
See Table of Contents, Bookmarks and Search Results
Set reading preferences
Increase font size
Decrease font size
Preferences / About

I am on Ubuntu 16.04 and installed Bookworms through:
sudo add-apt-repository ppa:bookworm-team/bookworm
sudo apt update && sudo apt install bookworm

**Comment by babluboy** [comment]
@Anne017 I have not really built bookworm on 16.04 - Launchpad only gives the option to build from Yaketty (16.10) so perhaps 16.04 is too old...someone has raised an issue for Bookworm not building on 16.04 (Issue #94 ) ...will be good to know how you built it on 16.04

Can you run bookworm in debug using `bookworm --debug` and put the output here...that might give a clue on what icons it is failing to load, etc.

**Comment by muralikodali** [comment]
i have also same issue.
debug report is attached as zip file.
[bwdebug.zip](https://github.com/babluboy/bookworm/files/1180005/bwdebug.zip)

**Comment by babluboy** [comment]
@muralikodali I could not see an issue from the debug log. Can you please post a screen shot showing the missing icons. Based on that I will ask you to check for the specific icon which are missing. I'm suspecting this to be a icon name difference between Elementary OS and Ubuntu 16.04 (Please confirm if you are running Bookworm on Ubuntu 16.04)

**Comment by Anne017** [comment]
![capture](https://user-images.githubusercontent.com/17686836/28683274-4c2052a8-7300-11e7-87b2-9b58d99aed63.png)

**Comment by babluboy** [comment]
Many thanks for the screenshot. All the missing icons are those that I'm using from the elementary icon set - I guess I should add some code to check if the icon is missing on the OS, there should be a fall back to load it from the bookworm icon data.
I will update here when I have done the changes and pushed to the stable PPA

**Comment by babluboy** [comment]
Pushed a change with fallback icons for all icons which were being loaded from the theme. This should resolve the missing icons shown in the ubuntu screenshot. Currently I have started the build on the daily ppa. Will spin a Ubuntu VM tomorrow and test this and then push to the stable PPA...

**Comment by babluboy** [comment]
Looks like the changes are working fine....on my Ubuntu 16.04.2 VM I can see that the "No icon image" is no longer appearing...will push to stable PPA tomorrow
![screenshot from 2017-08-02 23-25-34](https://user-images.githubusercontent.com/14061478/28898110-0626853e-77dc-11e7-910a-b2f006b51a54.png)
...

**Comment by babluboy** [comment]
Pushed to the stable PPA (ppa:bookworm-team/bookworm) as version 0.9.1
Please re-open if you still see the issue after updating on Ubuntu 16.04
